/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.api;

import bp4.mastercom_api_client.ApiException;
import bp4.mastercom_api_client.model.Errors;
import bp4.mastercom_api_client.model.ReconReportDataAcknowledgeRequest;
import bp4.mastercom_api_client.model.ReconReportDataAcknowledgeResponse;
import bp4.mastercom_api_client.model.ReconReportDataRetrivalResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReconciliationApi
 */
@Disabled
public class ReconciliationApiTest {

    private final ReconciliationApi api = new ReconciliationApi();

    /**
     * An issuer or acquirer uses this endpoint to request that Mastercom generate a reconciliation report or enhanced reconciliation report for a specified date range.   Note: The issuer or acquirer receives a unique report identifier in the response. Using the unique report identifier from this endpoint, the issuer or acquirer then retrieves the report from the Retrieve Reconciliation Report endpoint.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void reconReportDataAcknowledgeTest() throws ApiException {
        ReconReportDataAcknowledgeRequest reconDataRequest = null;
        ReconReportDataAcknowledgeResponse response = api.reconReportDataAcknowledge(reconDataRequest);
        // TODO: test validations
    }

    /**
     * An issuer or acquirer uses this endpoint to retrieve a reconciliation report or enhanced reconciliation report.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void reconReportDataRetrievalTest() throws ApiException {
        String reportIdentifier = null;
        ReconReportDataRetrivalResponse response = api.reconReportDataRetrieval(reportIdentifier);
        // TODO: test validations
    }

}
