/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import bp4.mastercom_api_client.JSON;

/**
 * AcquirerFulfillmentRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T19:57:39.604201-03:00[America/Buenos_Aires]")
public class AcquirerFulfillmentRequest {
  /**
   * Acquirer Response Code.   NOTE: Acquirers can no longer respond to retrieval requests using the existing process in production, except for transactions related to U.S. healthcare.   NOTE: Below acquirerResponseCd codes will be accepted starting on February 26th, 2023.    A - Funds Movement Request, B - Refunded, C - Initiating Refund, E - Reject Collaboration, F - IIAS Unfulfillable, G - IIAS Invalid request information, H - IIAS Fulfilled outside MasterCom system   Length: 1   Valid Values/Format: A - Funds Movement Request, B - Refunded, C - Initiating Refund, E - Reject Collaboration, F - IIAS Unfulfillable, G - IIAS Invalid request information, H - IIAS Fulfilled outside MasterCom system
   */
  @JsonAdapter(AcquirerResponseCdEnum.Adapter.class)
  public enum AcquirerResponseCdEnum {
    A("A"),
    
    B("B"),
    
    C("C"),
    
    E("E"),
    
    F("F"),
    
    G("G"),
    
    H("H");

    private String value;

    AcquirerResponseCdEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AcquirerResponseCdEnum fromValue(String value) {
      for (AcquirerResponseCdEnum b : AcquirerResponseCdEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AcquirerResponseCdEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AcquirerResponseCdEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AcquirerResponseCdEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AcquirerResponseCdEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ACQUIRER_RESPONSE_CD = "acquirerResponseCd";
  @SerializedName(SERIALIZED_NAME_ACQUIRER_RESPONSE_CD)
  private AcquirerResponseCdEnum acquirerResponseCd;

  public static final String SERIALIZED_NAME_REFUND_REVERSAL_TYPE = "refundReversalType";
  @SerializedName(SERIALIZED_NAME_REFUND_REVERSAL_TYPE)
  private String refundReversalType;

  public static final String SERIALIZED_NAME_REFUND_REVERSAL_DATE = "refundReversalDate";
  @SerializedName(SERIALIZED_NAME_REFUND_REVERSAL_DATE)
  private String refundReversalDate;

  public static final String SERIALIZED_NAME_REFUND_REVERSAL_AMOUNT = "refundReversalAmount";
  @SerializedName(SERIALIZED_NAME_REFUND_REVERSAL_AMOUNT)
  private String refundReversalAmount;

  public static final String SERIALIZED_NAME_REFUND_REVERSAL_CURRENCY = "refundReversalCurrency";
  @SerializedName(SERIALIZED_NAME_REFUND_REVERSAL_CURRENCY)
  private String refundReversalCurrency;

  public static final String SERIALIZED_NAME_REFUND_REVERSAL_REFERENCE_ID = "refundReversalReferenceId";
  @SerializedName(SERIALIZED_NAME_REFUND_REVERSAL_REFERENCE_ID)
  private String refundReversalReferenceId;

  public static final String SERIALIZED_NAME_MEMO = "memo";
  @SerializedName(SERIALIZED_NAME_MEMO)
  private String memo;

  public AcquirerFulfillmentRequest() {
  }

  public AcquirerFulfillmentRequest acquirerResponseCd(AcquirerResponseCdEnum acquirerResponseCd) {
    
    this.acquirerResponseCd = acquirerResponseCd;
    return this;
  }

   /**
   * Acquirer Response Code.   NOTE: Acquirers can no longer respond to retrieval requests using the existing process in production, except for transactions related to U.S. healthcare.   NOTE: Below acquirerResponseCd codes will be accepted starting on February 26th, 2023.    A - Funds Movement Request, B - Refunded, C - Initiating Refund, E - Reject Collaboration, F - IIAS Unfulfillable, G - IIAS Invalid request information, H - IIAS Fulfilled outside MasterCom system   Length: 1   Valid Values/Format: A - Funds Movement Request, B - Refunded, C - Initiating Refund, E - Reject Collaboration, F - IIAS Unfulfillable, G - IIAS Invalid request information, H - IIAS Fulfilled outside MasterCom system
   * @return acquirerResponseCd
  **/
  @javax.annotation.Nonnull
  public AcquirerResponseCdEnum getAcquirerResponseCd() {
    return acquirerResponseCd;
  }


  public void setAcquirerResponseCd(AcquirerResponseCdEnum acquirerResponseCd) {
    this.acquirerResponseCd = acquirerResponseCd;
  }


  public AcquirerFulfillmentRequest refundReversalType(String refundReversalType) {
    
    this.refundReversalType = refundReversalType;
    return this;
  }

   /**
   * Refund/Reversal Type.   CONDITIONAL: This field is not valid if acquirerResponseCd is A, E, F, G or H.   If acquirerResponseCd is C, then CREDIT VOUCHER is not a valid value.   Required if acquirerResponseCd is B.   Length: 6-14   Valid Values/Format: REFUND, CREDIT VOUCHER
   * @return refundReversalType
  **/
  @javax.annotation.Nullable
  public String getRefundReversalType() {
    return refundReversalType;
  }


  public void setRefundReversalType(String refundReversalType) {
    this.refundReversalType = refundReversalType;
  }


  public AcquirerFulfillmentRequest refundReversalDate(String refundReversalDate) {
    
    this.refundReversalDate = refundReversalDate;
    return this;
  }

   /**
   * Refund/Reversal Date.   CONDITIONAL: This field is not valid if acquirerResponseCd is A, E, F, G or H.   Not valid if refundReversalType is not provided.   Required if acquirerResponseCd is B or C and refundReversalType is REFUND.   Length: 16   Valid Values/Format: Date (yyyy-MM-ddTHH:mm)
   * @return refundReversalDate
  **/
  @javax.annotation.Nullable
  public String getRefundReversalDate() {
    return refundReversalDate;
  }


  public void setRefundReversalDate(String refundReversalDate) {
    this.refundReversalDate = refundReversalDate;
  }


  public AcquirerFulfillmentRequest refundReversalAmount(String refundReversalAmount) {
    
    this.refundReversalAmount = refundReversalAmount;
    return this;
  }

   /**
   * Refund/Reversal Amount.   CONDITIONAL: This field is not valid if acquirerResponseCd is A, E, F, G or H.   This field is only valid if acquirerResponseCd is B and refundReversalType is CREDIT VOUCHER.   Not valid if refundReversalType is not provided.   Valid Values/Format: Numeric
   * @return refundReversalAmount
  **/
  @javax.annotation.Nullable
  public String getRefundReversalAmount() {
    return refundReversalAmount;
  }


  public void setRefundReversalAmount(String refundReversalAmount) {
    this.refundReversalAmount = refundReversalAmount;
  }


  public AcquirerFulfillmentRequest refundReversalCurrency(String refundReversalCurrency) {
    
    this.refundReversalCurrency = refundReversalCurrency;
    return this;
  }

   /**
   * Refund/Reversal Currency.   CONDITIONAL: This field is not valid if acquirerResponseCd is A, E, F, G or H.   This field is only valid if acquirerResponseCd is B and refundReversalType is CREDIT VOUCHER.   Not valid if refundReversalType is not provided.   Length: 3   Valid Values/Format: A-Z (Uppercase Alphabetic Letter)
   * @return refundReversalCurrency
  **/
  @javax.annotation.Nullable
  public String getRefundReversalCurrency() {
    return refundReversalCurrency;
  }


  public void setRefundReversalCurrency(String refundReversalCurrency) {
    this.refundReversalCurrency = refundReversalCurrency;
  }


  public AcquirerFulfillmentRequest refundReversalReferenceId(String refundReversalReferenceId) {
    
    this.refundReversalReferenceId = refundReversalReferenceId;
    return this;
  }

   /**
   * For Transaction type Authorized transactions:&lt;br&gt; First 12 positions of Data Element (DE) 63 (Network Data) from one of the following:&lt;br&gt; – Authorized refund message (Authorization Request Response/0110 or Financial Transaction Request Response/0210)&lt;br&gt; – Reversal message (Reversal Request Response/ 0410 or Acquirer Reversal Advice Response/ 0430)&lt;br&gt; – Automated fuel dispenser transaction (MCC &#x3D; 5542 and CAT Level 2) (Authorization Advice Response/0130)   For Transaction type Cleared transactions:&lt;br&gt;  DE 63 (Network Data), subfield 2 (Trace ID) in the First Presentment/1240 message   For Transaction type Not authorized but cleared transactions:&lt;br&gt;  Either Private Data Subelement (PDS) 0105 (File ID) or PDS 158, subfield 5 (Central Site Business Date) and subfield 6 (Business Cycle) with no spaces   CONDITIONAL: This field is not valid if acquirerResponseCd is A, E, F, G or H.   Not valid if refundReversalType is not provided.   Required if acquirerResponseCd is B or C and refundReversalType is REFUND.   Length: 8-25   Valid Values/Format: Alphanumeric
   * @return refundReversalReferenceId
  **/
  @javax.annotation.Nullable
  public String getRefundReversalReferenceId() {
    return refundReversalReferenceId;
  }


  public void setRefundReversalReferenceId(String refundReversalReferenceId) {
    this.refundReversalReferenceId = refundReversalReferenceId;
  }


  public AcquirerFulfillmentRequest memo(String memo) {
    
    this.memo = memo;
    return this;
  }

   /**
   * Memo.   Length: 1-100   Valid Values/Format: Alphanumeric, Special Char (~!@#$%^&amp;*()_+{}|:\&quot;&lt;&gt;?,./;&#39;[]-&#x3D;)
   * @return memo
  **/
  @javax.annotation.Nullable
  public String getMemo() {
    return memo;
  }


  public void setMemo(String memo) {
    this.memo = memo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AcquirerFulfillmentRequest acquirerFulfillmentRequest = (AcquirerFulfillmentRequest) o;
    return Objects.equals(this.acquirerResponseCd, acquirerFulfillmentRequest.acquirerResponseCd) &&
        Objects.equals(this.refundReversalType, acquirerFulfillmentRequest.refundReversalType) &&
        Objects.equals(this.refundReversalDate, acquirerFulfillmentRequest.refundReversalDate) &&
        Objects.equals(this.refundReversalAmount, acquirerFulfillmentRequest.refundReversalAmount) &&
        Objects.equals(this.refundReversalCurrency, acquirerFulfillmentRequest.refundReversalCurrency) &&
        Objects.equals(this.refundReversalReferenceId, acquirerFulfillmentRequest.refundReversalReferenceId) &&
        Objects.equals(this.memo, acquirerFulfillmentRequest.memo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acquirerResponseCd, refundReversalType, refundReversalDate, refundReversalAmount, refundReversalCurrency, refundReversalReferenceId, memo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcquirerFulfillmentRequest {\n");
    sb.append("    acquirerResponseCd: ").append(toIndentedString(acquirerResponseCd)).append("\n");
    sb.append("    refundReversalType: ").append(toIndentedString(refundReversalType)).append("\n");
    sb.append("    refundReversalDate: ").append(toIndentedString(refundReversalDate)).append("\n");
    sb.append("    refundReversalAmount: ").append(toIndentedString(refundReversalAmount)).append("\n");
    sb.append("    refundReversalCurrency: ").append(toIndentedString(refundReversalCurrency)).append("\n");
    sb.append("    refundReversalReferenceId: ").append(toIndentedString(refundReversalReferenceId)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("acquirerResponseCd");
    openapiFields.add("refundReversalType");
    openapiFields.add("refundReversalDate");
    openapiFields.add("refundReversalAmount");
    openapiFields.add("refundReversalCurrency");
    openapiFields.add("refundReversalReferenceId");
    openapiFields.add("memo");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("acquirerResponseCd");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AcquirerFulfillmentRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AcquirerFulfillmentRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AcquirerFulfillmentRequest is not found in the empty JSON string", AcquirerFulfillmentRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AcquirerFulfillmentRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AcquirerFulfillmentRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AcquirerFulfillmentRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("acquirerResponseCd").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `acquirerResponseCd` to be a primitive type in the JSON string but got `%s`", jsonObj.get("acquirerResponseCd").toString()));
      }
      if ((jsonObj.get("refundReversalType") != null && !jsonObj.get("refundReversalType").isJsonNull()) && !jsonObj.get("refundReversalType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refundReversalType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refundReversalType").toString()));
      }
      if ((jsonObj.get("refundReversalDate") != null && !jsonObj.get("refundReversalDate").isJsonNull()) && !jsonObj.get("refundReversalDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refundReversalDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refundReversalDate").toString()));
      }
      if ((jsonObj.get("refundReversalAmount") != null && !jsonObj.get("refundReversalAmount").isJsonNull()) && !jsonObj.get("refundReversalAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refundReversalAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refundReversalAmount").toString()));
      }
      if ((jsonObj.get("refundReversalCurrency") != null && !jsonObj.get("refundReversalCurrency").isJsonNull()) && !jsonObj.get("refundReversalCurrency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refundReversalCurrency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refundReversalCurrency").toString()));
      }
      if ((jsonObj.get("refundReversalReferenceId") != null && !jsonObj.get("refundReversalReferenceId").isJsonNull()) && !jsonObj.get("refundReversalReferenceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refundReversalReferenceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refundReversalReferenceId").toString()));
      }
      if ((jsonObj.get("memo") != null && !jsonObj.get("memo").isJsonNull()) && !jsonObj.get("memo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `memo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("memo").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AcquirerFulfillmentRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AcquirerFulfillmentRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AcquirerFulfillmentRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AcquirerFulfillmentRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AcquirerFulfillmentRequest>() {
           @Override
           public void write(JsonWriter out, AcquirerFulfillmentRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AcquirerFulfillmentRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AcquirerFulfillmentRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AcquirerFulfillmentRequest
  * @throws IOException if the JSON string is invalid with respect to AcquirerFulfillmentRequest
  */
  public static AcquirerFulfillmentRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AcquirerFulfillmentRequest.class);
  }

 /**
  * Convert an instance of AcquirerFulfillmentRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

