/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import java.util.Objects;
import bp4.mastercom_api_client.model.CaseFilingLifeCycle;
import bp4.mastercom_api_client.model.ChargebackDetails;
import bp4.mastercom_api_client.model.FeeDetails;
import bp4.mastercom_api_client.model.RetrievalSummary;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import bp4.mastercom_api_client.JSON;

/**
 * ClaimDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T19:57:39.604201-03:00[America/Buenos_Aires]")
public class ClaimDetail {
  public static final String SERIALIZED_NAME_ACQUIRER_ID = "acquirerId";
  @SerializedName(SERIALIZED_NAME_ACQUIRER_ID)
  private String acquirerId;

  public static final String SERIALIZED_NAME_ACQUIRER_REF_NUM = "acquirerRefNum";
  @SerializedName(SERIALIZED_NAME_ACQUIRER_REF_NUM)
  private String acquirerRefNum;

  public static final String SERIALIZED_NAME_PRIMARY_ACCOUNT_NUM = "primaryAccountNum";
  @SerializedName(SERIALIZED_NAME_PRIMARY_ACCOUNT_NUM)
  private String primaryAccountNum;

  public static final String SERIALIZED_NAME_CLAIM_ID = "claimId";
  @SerializedName(SERIALIZED_NAME_CLAIM_ID)
  private String claimId;

  public static final String SERIALIZED_NAME_CLAIM_TYPE = "claimType";
  @SerializedName(SERIALIZED_NAME_CLAIM_TYPE)
  private String claimType;

  public static final String SERIALIZED_NAME_CLAIM_VALUE = "claimValue";
  @SerializedName(SERIALIZED_NAME_CLAIM_VALUE)
  private String claimValue;

  public static final String SERIALIZED_NAME_STANDARD_CLAIMS = "standardClaims";
  @SerializedName(SERIALIZED_NAME_STANDARD_CLAIMS)
  private String standardClaims;

  public static final String SERIALIZED_NAME_CLEARING_DUE_DATE = "clearingDueDate";
  @SerializedName(SERIALIZED_NAME_CLEARING_DUE_DATE)
  private String clearingDueDate;

  public static final String SERIALIZED_NAME_CLEARING_NETWORK = "clearingNetwork";
  @SerializedName(SERIALIZED_NAME_CLEARING_NETWORK)
  private String clearingNetwork;

  public static final String SERIALIZED_NAME_CREATE_DATE = "createDate";
  @SerializedName(SERIALIZED_NAME_CREATE_DATE)
  private String createDate;

  public static final String SERIALIZED_NAME_DUE_DATE = "dueDate";
  @SerializedName(SERIALIZED_NAME_DUE_DATE)
  private String dueDate;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transactionId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  private String transactionId;

  public static final String SERIALIZED_NAME_IS_ACCURATE = "isAccurate";
  @SerializedName(SERIALIZED_NAME_IS_ACCURATE)
  private String isAccurate;

  public static final String SERIALIZED_NAME_IS_ACQUIRER = "isAcquirer";
  @SerializedName(SERIALIZED_NAME_IS_ACQUIRER)
  private String isAcquirer;

  public static final String SERIALIZED_NAME_IS_ISSUER = "isIssuer";
  @SerializedName(SERIALIZED_NAME_IS_ISSUER)
  private String isIssuer;

  public static final String SERIALIZED_NAME_IS_OPEN = "isOpen";
  @SerializedName(SERIALIZED_NAME_IS_OPEN)
  private String isOpen;

  public static final String SERIALIZED_NAME_ISSUER_ID = "issuerId";
  @SerializedName(SERIALIZED_NAME_ISSUER_ID)
  private String issuerId;

  public static final String SERIALIZED_NAME_LAST_MODIFIED_BY = "lastModifiedBy";
  @SerializedName(SERIALIZED_NAME_LAST_MODIFIED_BY)
  private String lastModifiedBy;

  public static final String SERIALIZED_NAME_LAST_MODIFIED_DATE = "lastModifiedDate";
  @SerializedName(SERIALIZED_NAME_LAST_MODIFIED_DATE)
  private String lastModifiedDate;

  public static final String SERIALIZED_NAME_MERCHANT_ID = "merchantId";
  @SerializedName(SERIALIZED_NAME_MERCHANT_ID)
  private String merchantId;

  public static final String SERIALIZED_NAME_QUEUE_NAME = "queueName";
  @SerializedName(SERIALIZED_NAME_QUEUE_NAME)
  private String queueName;

  public static final String SERIALIZED_NAME_SWITCH_SERIAL_NUMBER = "switchSerialNumber";
  @SerializedName(SERIALIZED_NAME_SWITCH_SERIAL_NUMBER)
  private String switchSerialNumber;

  public static final String SERIALIZED_NAME_CASE_FILING_DETAILS = "caseFilingDetails";
  @SerializedName(SERIALIZED_NAME_CASE_FILING_DETAILS)
  private CaseFilingLifeCycle caseFilingDetails;

  public static final String SERIALIZED_NAME_RETRIEVAL_DETAILS = "retrievalDetails";
  @SerializedName(SERIALIZED_NAME_RETRIEVAL_DETAILS)
  private RetrievalSummary retrievalDetails;

  public static final String SERIALIZED_NAME_CHARGEBACK_DETAILS = "chargebackDetails";
  @SerializedName(SERIALIZED_NAME_CHARGEBACK_DETAILS)
  private List<ChargebackDetails> chargebackDetails;

  public static final String SERIALIZED_NAME_FEE_DETAILS = "feeDetails";
  @SerializedName(SERIALIZED_NAME_FEE_DETAILS)
  private List<FeeDetails> feeDetails;

  public static final String SERIALIZED_NAME_RETRIEVAL_DETAILS_LIST = "retrievalDetailsList";
  @SerializedName(SERIALIZED_NAME_RETRIEVAL_DETAILS_LIST)
  private List<RetrievalSummary> retrievalDetailsList;

  public ClaimDetail() {
  }

  public ClaimDetail acquirerId(String acquirerId) {
    
    this.acquirerId = acquirerId;
    return this;
  }

   /**
   * Acquirer Inst Id
   * @return acquirerId
  **/
  @javax.annotation.Nullable
  public String getAcquirerId() {
    return acquirerId;
  }


  public void setAcquirerId(String acquirerId) {
    this.acquirerId = acquirerId;
  }


  public ClaimDetail acquirerRefNum(String acquirerRefNum) {
    
    this.acquirerRefNum = acquirerRefNum;
    return this;
  }

   /**
   * Acquirer Reference Number
   * @return acquirerRefNum
  **/
  @javax.annotation.Nullable
  public String getAcquirerRefNum() {
    return acquirerRefNum;
  }


  public void setAcquirerRefNum(String acquirerRefNum) {
    this.acquirerRefNum = acquirerRefNum;
  }


  public ClaimDetail primaryAccountNum(String primaryAccountNum) {
    
    this.primaryAccountNum = primaryAccountNum;
    return this;
  }

   /**
   * Card Number for which the Claim is opened
   * @return primaryAccountNum
  **/
  @javax.annotation.Nullable
  public String getPrimaryAccountNum() {
    return primaryAccountNum;
  }


  public void setPrimaryAccountNum(String primaryAccountNum) {
    this.primaryAccountNum = primaryAccountNum;
  }


  public ClaimDetail claimId(String claimId) {
    
    this.claimId = claimId;
    return this;
  }

   /**
   * Claim Id
   * @return claimId
  **/
  @javax.annotation.Nullable
  public String getClaimId() {
    return claimId;
  }


  public void setClaimId(String claimId) {
    this.claimId = claimId;
  }


  public ClaimDetail claimType(String claimType) {
    
    this.claimType = claimType;
    return this;
  }

   /**
   * Claim Type
   * @return claimType
  **/
  @javax.annotation.Nullable
  public String getClaimType() {
    return claimType;
  }


  public void setClaimType(String claimType) {
    this.claimType = claimType;
  }


  public ClaimDetail claimValue(String claimValue) {
    
    this.claimValue = claimValue;
    return this;
  }

   /**
   * The value of the claim
   * @return claimValue
  **/
  @javax.annotation.Nullable
  public String getClaimValue() {
    return claimValue;
  }


  public void setClaimValue(String claimValue) {
    this.claimValue = claimValue;
  }


  public ClaimDetail standardClaims(String standardClaims) {
    
    this.standardClaims = standardClaims;
    return this;
  }

   /**
   * Contain all Standard Claim Ids associated with the claimType of CaseFiling.  This field will contain a comma delimited list.
   * @return standardClaims
  **/
  @javax.annotation.Nullable
  public String getStandardClaims() {
    return standardClaims;
  }


  public void setStandardClaims(String standardClaims) {
    this.standardClaims = standardClaims;
  }


  public ClaimDetail clearingDueDate(String clearingDueDate) {
    
    this.clearingDueDate = clearingDueDate;
    return this;
  }

   /**
   * The clearing due date of the claim
   * @return clearingDueDate
  **/
  @javax.annotation.Nullable
  public String getClearingDueDate() {
    return clearingDueDate;
  }


  public void setClearingDueDate(String clearingDueDate) {
    this.clearingDueDate = clearingDueDate;
  }


  public ClaimDetail clearingNetwork(String clearingNetwork) {
    
    this.clearingNetwork = clearingNetwork;
    return this;
  }

   /**
   * Clearing Network
   * @return clearingNetwork
  **/
  @javax.annotation.Nullable
  public String getClearingNetwork() {
    return clearingNetwork;
  }


  public void setClearingNetwork(String clearingNetwork) {
    this.clearingNetwork = clearingNetwork;
  }


  public ClaimDetail createDate(String createDate) {
    
    this.createDate = createDate;
    return this;
  }

   /**
   * This is the date of the Claim creation
   * @return createDate
  **/
  @javax.annotation.Nullable
  public String getCreateDate() {
    return createDate;
  }


  public void setCreateDate(String createDate) {
    this.createDate = createDate;
  }


  public ClaimDetail dueDate(String dueDate) {
    
    this.dueDate = dueDate;
    return this;
  }

   /**
   * The due date of the claim
   * @return dueDate
  **/
  @javax.annotation.Nullable
  public String getDueDate() {
    return dueDate;
  }


  public void setDueDate(String dueDate) {
    this.dueDate = dueDate;
  }


  public ClaimDetail transactionId(String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * An alphanumeric identifier that ties the clearingTransactionId and authTransactionId to the Claim. The format is TI:&lt;ClearingSummary.transactionId&gt;#&lt;AuthorizationSummary.transactionId&gt;
   * @return transactionId
  **/
  @javax.annotation.Nullable
  public String getTransactionId() {
    return transactionId;
  }


  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public ClaimDetail isAccurate(String isAccurate) {
    
    this.isAccurate = isAccurate;
    return this;
  }

   /**
   * True if the claim value is accurate
   * @return isAccurate
  **/
  @javax.annotation.Nullable
  public String getIsAccurate() {
    return isAccurate;
  }


  public void setIsAccurate(String isAccurate) {
    this.isAccurate = isAccurate;
  }


  public ClaimDetail isAcquirer(String isAcquirer) {
    
    this.isAcquirer = isAcquirer;
    return this;
  }

   /**
   * True if the claim is acquirer
   * @return isAcquirer
  **/
  @javax.annotation.Nullable
  public String getIsAcquirer() {
    return isAcquirer;
  }


  public void setIsAcquirer(String isAcquirer) {
    this.isAcquirer = isAcquirer;
  }


  public ClaimDetail isIssuer(String isIssuer) {
    
    this.isIssuer = isIssuer;
    return this;
  }

   /**
   * True if the claim is issuer
   * @return isIssuer
  **/
  @javax.annotation.Nullable
  public String getIsIssuer() {
    return isIssuer;
  }


  public void setIsIssuer(String isIssuer) {
    this.isIssuer = isIssuer;
  }


  public ClaimDetail isOpen(String isOpen) {
    
    this.isOpen = isOpen;
    return this;
  }

   /**
   * True if the claim is open
   * @return isOpen
  **/
  @javax.annotation.Nullable
  public String getIsOpen() {
    return isOpen;
  }


  public void setIsOpen(String isOpen) {
    this.isOpen = isOpen;
  }


  public ClaimDetail issuerId(String issuerId) {
    
    this.issuerId = issuerId;
    return this;
  }

   /**
   * The issuer institution identifier
   * @return issuerId
  **/
  @javax.annotation.Nullable
  public String getIssuerId() {
    return issuerId;
  }


  public void setIssuerId(String issuerId) {
    this.issuerId = issuerId;
  }


  public ClaimDetail lastModifiedBy(String lastModifiedBy) {
    
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * User who signed this event
   * @return lastModifiedBy
  **/
  @javax.annotation.Nullable
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }


  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }


  public ClaimDetail lastModifiedDate(String lastModifiedDate) {
    
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * The date of the last claim modification
   * @return lastModifiedDate
  **/
  @javax.annotation.Nullable
  public String getLastModifiedDate() {
    return lastModifiedDate;
  }


  public void setLastModifiedDate(String lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }


  public ClaimDetail merchantId(String merchantId) {
    
    this.merchantId = merchantId;
    return this;
  }

   /**
   * Returns the related merchant identifier
   * @return merchantId
  **/
  @javax.annotation.Nullable
  public String getMerchantId() {
    return merchantId;
  }


  public void setMerchantId(String merchantId) {
    this.merchantId = merchantId;
  }


  public ClaimDetail queueName(String queueName) {
    
    this.queueName = queueName;
    return this;
  }

   /**
   * The queue name to which the claim has been allocated
   * @return queueName
  **/
  @javax.annotation.Nullable
  public String getQueueName() {
    return queueName;
  }


  public void setQueueName(String queueName) {
    this.queueName = queueName;
  }


  public ClaimDetail switchSerialNumber(String switchSerialNumber) {
    
    this.switchSerialNumber = switchSerialNumber;
    return this;
  }

   /**
   * The Switch Serial Number is a unique transaction identification number generated (or assigned) by the Single Message System
   * @return switchSerialNumber
  **/
  @javax.annotation.Nullable
  public String getSwitchSerialNumber() {
    return switchSerialNumber;
  }


  public void setSwitchSerialNumber(String switchSerialNumber) {
    this.switchSerialNumber = switchSerialNumber;
  }


  public ClaimDetail caseFilingDetails(CaseFilingLifeCycle caseFilingDetails) {
    
    this.caseFilingDetails = caseFilingDetails;
    return this;
  }

   /**
   * Get caseFilingDetails
   * @return caseFilingDetails
  **/
  @javax.annotation.Nullable
  public CaseFilingLifeCycle getCaseFilingDetails() {
    return caseFilingDetails;
  }


  public void setCaseFilingDetails(CaseFilingLifeCycle caseFilingDetails) {
    this.caseFilingDetails = caseFilingDetails;
  }


  public ClaimDetail retrievalDetails(RetrievalSummary retrievalDetails) {
    
    this.retrievalDetails = retrievalDetails;
    return this;
  }

   /**
   * Get retrievalDetails
   * @return retrievalDetails
  **/
  @javax.annotation.Nullable
  public RetrievalSummary getRetrievalDetails() {
    return retrievalDetails;
  }


  public void setRetrievalDetails(RetrievalSummary retrievalDetails) {
    this.retrievalDetails = retrievalDetails;
  }


  public ClaimDetail chargebackDetails(List<ChargebackDetails> chargebackDetails) {
    
    this.chargebackDetails = chargebackDetails;
    return this;
  }

  public ClaimDetail addChargebackDetailsItem(ChargebackDetails chargebackDetailsItem) {
    if (this.chargebackDetails == null) {
      this.chargebackDetails = new ArrayList<>();
    }
    this.chargebackDetails.add(chargebackDetailsItem);
    return this;
  }

   /**
   * Get chargebackDetails
   * @return chargebackDetails
  **/
  @javax.annotation.Nullable
  public List<ChargebackDetails> getChargebackDetails() {
    return chargebackDetails;
  }


  public void setChargebackDetails(List<ChargebackDetails> chargebackDetails) {
    this.chargebackDetails = chargebackDetails;
  }


  public ClaimDetail feeDetails(List<FeeDetails> feeDetails) {
    
    this.feeDetails = feeDetails;
    return this;
  }

  public ClaimDetail addFeeDetailsItem(FeeDetails feeDetailsItem) {
    if (this.feeDetails == null) {
      this.feeDetails = new ArrayList<>();
    }
    this.feeDetails.add(feeDetailsItem);
    return this;
  }

   /**
   * Get feeDetails
   * @return feeDetails
  **/
  @javax.annotation.Nullable
  public List<FeeDetails> getFeeDetails() {
    return feeDetails;
  }


  public void setFeeDetails(List<FeeDetails> feeDetails) {
    this.feeDetails = feeDetails;
  }


  public ClaimDetail retrievalDetailsList(List<RetrievalSummary> retrievalDetailsList) {
    
    this.retrievalDetailsList = retrievalDetailsList;
    return this;
  }

  public ClaimDetail addRetrievalDetailsListItem(RetrievalSummary retrievalDetailsListItem) {
    if (this.retrievalDetailsList == null) {
      this.retrievalDetailsList = new ArrayList<>();
    }
    this.retrievalDetailsList.add(retrievalDetailsListItem);
    return this;
  }

   /**
   * Get retrievalDetailsList
   * @return retrievalDetailsList
  **/
  @javax.annotation.Nullable
  public List<RetrievalSummary> getRetrievalDetailsList() {
    return retrievalDetailsList;
  }


  public void setRetrievalDetailsList(List<RetrievalSummary> retrievalDetailsList) {
    this.retrievalDetailsList = retrievalDetailsList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClaimDetail claimDetail = (ClaimDetail) o;
    return Objects.equals(this.acquirerId, claimDetail.acquirerId) &&
        Objects.equals(this.acquirerRefNum, claimDetail.acquirerRefNum) &&
        Objects.equals(this.primaryAccountNum, claimDetail.primaryAccountNum) &&
        Objects.equals(this.claimId, claimDetail.claimId) &&
        Objects.equals(this.claimType, claimDetail.claimType) &&
        Objects.equals(this.claimValue, claimDetail.claimValue) &&
        Objects.equals(this.standardClaims, claimDetail.standardClaims) &&
        Objects.equals(this.clearingDueDate, claimDetail.clearingDueDate) &&
        Objects.equals(this.clearingNetwork, claimDetail.clearingNetwork) &&
        Objects.equals(this.createDate, claimDetail.createDate) &&
        Objects.equals(this.dueDate, claimDetail.dueDate) &&
        Objects.equals(this.transactionId, claimDetail.transactionId) &&
        Objects.equals(this.isAccurate, claimDetail.isAccurate) &&
        Objects.equals(this.isAcquirer, claimDetail.isAcquirer) &&
        Objects.equals(this.isIssuer, claimDetail.isIssuer) &&
        Objects.equals(this.isOpen, claimDetail.isOpen) &&
        Objects.equals(this.issuerId, claimDetail.issuerId) &&
        Objects.equals(this.lastModifiedBy, claimDetail.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDate, claimDetail.lastModifiedDate) &&
        Objects.equals(this.merchantId, claimDetail.merchantId) &&
        Objects.equals(this.queueName, claimDetail.queueName) &&
        Objects.equals(this.switchSerialNumber, claimDetail.switchSerialNumber) &&
        Objects.equals(this.caseFilingDetails, claimDetail.caseFilingDetails) &&
        Objects.equals(this.retrievalDetails, claimDetail.retrievalDetails) &&
        Objects.equals(this.chargebackDetails, claimDetail.chargebackDetails) &&
        Objects.equals(this.feeDetails, claimDetail.feeDetails) &&
        Objects.equals(this.retrievalDetailsList, claimDetail.retrievalDetailsList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acquirerId, acquirerRefNum, primaryAccountNum, claimId, claimType, claimValue, standardClaims, clearingDueDate, clearingNetwork, createDate, dueDate, transactionId, isAccurate, isAcquirer, isIssuer, isOpen, issuerId, lastModifiedBy, lastModifiedDate, merchantId, queueName, switchSerialNumber, caseFilingDetails, retrievalDetails, chargebackDetails, feeDetails, retrievalDetailsList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClaimDetail {\n");
    sb.append("    acquirerId: ").append(toIndentedString(acquirerId)).append("\n");
    sb.append("    acquirerRefNum: ").append(toIndentedString(acquirerRefNum)).append("\n");
    sb.append("    primaryAccountNum: ").append(toIndentedString(primaryAccountNum)).append("\n");
    sb.append("    claimId: ").append(toIndentedString(claimId)).append("\n");
    sb.append("    claimType: ").append(toIndentedString(claimType)).append("\n");
    sb.append("    claimValue: ").append(toIndentedString(claimValue)).append("\n");
    sb.append("    standardClaims: ").append(toIndentedString(standardClaims)).append("\n");
    sb.append("    clearingDueDate: ").append(toIndentedString(clearingDueDate)).append("\n");
    sb.append("    clearingNetwork: ").append(toIndentedString(clearingNetwork)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    isAccurate: ").append(toIndentedString(isAccurate)).append("\n");
    sb.append("    isAcquirer: ").append(toIndentedString(isAcquirer)).append("\n");
    sb.append("    isIssuer: ").append(toIndentedString(isIssuer)).append("\n");
    sb.append("    isOpen: ").append(toIndentedString(isOpen)).append("\n");
    sb.append("    issuerId: ").append(toIndentedString(issuerId)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    queueName: ").append(toIndentedString(queueName)).append("\n");
    sb.append("    switchSerialNumber: ").append(toIndentedString(switchSerialNumber)).append("\n");
    sb.append("    caseFilingDetails: ").append(toIndentedString(caseFilingDetails)).append("\n");
    sb.append("    retrievalDetails: ").append(toIndentedString(retrievalDetails)).append("\n");
    sb.append("    chargebackDetails: ").append(toIndentedString(chargebackDetails)).append("\n");
    sb.append("    feeDetails: ").append(toIndentedString(feeDetails)).append("\n");
    sb.append("    retrievalDetailsList: ").append(toIndentedString(retrievalDetailsList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("acquirerId");
    openapiFields.add("acquirerRefNum");
    openapiFields.add("primaryAccountNum");
    openapiFields.add("claimId");
    openapiFields.add("claimType");
    openapiFields.add("claimValue");
    openapiFields.add("standardClaims");
    openapiFields.add("clearingDueDate");
    openapiFields.add("clearingNetwork");
    openapiFields.add("createDate");
    openapiFields.add("dueDate");
    openapiFields.add("transactionId");
    openapiFields.add("isAccurate");
    openapiFields.add("isAcquirer");
    openapiFields.add("isIssuer");
    openapiFields.add("isOpen");
    openapiFields.add("issuerId");
    openapiFields.add("lastModifiedBy");
    openapiFields.add("lastModifiedDate");
    openapiFields.add("merchantId");
    openapiFields.add("queueName");
    openapiFields.add("switchSerialNumber");
    openapiFields.add("caseFilingDetails");
    openapiFields.add("retrievalDetails");
    openapiFields.add("chargebackDetails");
    openapiFields.add("feeDetails");
    openapiFields.add("retrievalDetailsList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ClaimDetail
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ClaimDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ClaimDetail is not found in the empty JSON string", ClaimDetail.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ClaimDetail.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ClaimDetail` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("acquirerId") != null && !jsonObj.get("acquirerId").isJsonNull()) && !jsonObj.get("acquirerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `acquirerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("acquirerId").toString()));
      }
      if ((jsonObj.get("acquirerRefNum") != null && !jsonObj.get("acquirerRefNum").isJsonNull()) && !jsonObj.get("acquirerRefNum").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `acquirerRefNum` to be a primitive type in the JSON string but got `%s`", jsonObj.get("acquirerRefNum").toString()));
      }
      if ((jsonObj.get("primaryAccountNum") != null && !jsonObj.get("primaryAccountNum").isJsonNull()) && !jsonObj.get("primaryAccountNum").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `primaryAccountNum` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primaryAccountNum").toString()));
      }
      if ((jsonObj.get("claimId") != null && !jsonObj.get("claimId").isJsonNull()) && !jsonObj.get("claimId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `claimId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimId").toString()));
      }
      if ((jsonObj.get("claimType") != null && !jsonObj.get("claimType").isJsonNull()) && !jsonObj.get("claimType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `claimType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimType").toString()));
      }
      if ((jsonObj.get("claimValue") != null && !jsonObj.get("claimValue").isJsonNull()) && !jsonObj.get("claimValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `claimValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimValue").toString()));
      }
      if ((jsonObj.get("standardClaims") != null && !jsonObj.get("standardClaims").isJsonNull()) && !jsonObj.get("standardClaims").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `standardClaims` to be a primitive type in the JSON string but got `%s`", jsonObj.get("standardClaims").toString()));
      }
      if ((jsonObj.get("clearingDueDate") != null && !jsonObj.get("clearingDueDate").isJsonNull()) && !jsonObj.get("clearingDueDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clearingDueDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clearingDueDate").toString()));
      }
      if ((jsonObj.get("clearingNetwork") != null && !jsonObj.get("clearingNetwork").isJsonNull()) && !jsonObj.get("clearingNetwork").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clearingNetwork` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clearingNetwork").toString()));
      }
      if ((jsonObj.get("createDate") != null && !jsonObj.get("createDate").isJsonNull()) && !jsonObj.get("createDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createDate").toString()));
      }
      if ((jsonObj.get("dueDate") != null && !jsonObj.get("dueDate").isJsonNull()) && !jsonObj.get("dueDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dueDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dueDate").toString()));
      }
      if ((jsonObj.get("transactionId") != null && !jsonObj.get("transactionId").isJsonNull()) && !jsonObj.get("transactionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionId").toString()));
      }
      if ((jsonObj.get("isAccurate") != null && !jsonObj.get("isAccurate").isJsonNull()) && !jsonObj.get("isAccurate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isAccurate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isAccurate").toString()));
      }
      if ((jsonObj.get("isAcquirer") != null && !jsonObj.get("isAcquirer").isJsonNull()) && !jsonObj.get("isAcquirer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isAcquirer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isAcquirer").toString()));
      }
      if ((jsonObj.get("isIssuer") != null && !jsonObj.get("isIssuer").isJsonNull()) && !jsonObj.get("isIssuer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isIssuer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isIssuer").toString()));
      }
      if ((jsonObj.get("isOpen") != null && !jsonObj.get("isOpen").isJsonNull()) && !jsonObj.get("isOpen").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isOpen` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isOpen").toString()));
      }
      if ((jsonObj.get("issuerId") != null && !jsonObj.get("issuerId").isJsonNull()) && !jsonObj.get("issuerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `issuerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("issuerId").toString()));
      }
      if ((jsonObj.get("lastModifiedBy") != null && !jsonObj.get("lastModifiedBy").isJsonNull()) && !jsonObj.get("lastModifiedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastModifiedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastModifiedBy").toString()));
      }
      if ((jsonObj.get("lastModifiedDate") != null && !jsonObj.get("lastModifiedDate").isJsonNull()) && !jsonObj.get("lastModifiedDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastModifiedDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastModifiedDate").toString()));
      }
      if ((jsonObj.get("merchantId") != null && !jsonObj.get("merchantId").isJsonNull()) && !jsonObj.get("merchantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantId").toString()));
      }
      if ((jsonObj.get("queueName") != null && !jsonObj.get("queueName").isJsonNull()) && !jsonObj.get("queueName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `queueName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("queueName").toString()));
      }
      if ((jsonObj.get("switchSerialNumber") != null && !jsonObj.get("switchSerialNumber").isJsonNull()) && !jsonObj.get("switchSerialNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `switchSerialNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("switchSerialNumber").toString()));
      }
      // validate the optional field `caseFilingDetails`
      if (jsonObj.get("caseFilingDetails") != null && !jsonObj.get("caseFilingDetails").isJsonNull()) {
        CaseFilingLifeCycle.validateJsonElement(jsonObj.get("caseFilingDetails"));
      }
      // validate the optional field `retrievalDetails`
      if (jsonObj.get("retrievalDetails") != null && !jsonObj.get("retrievalDetails").isJsonNull()) {
        RetrievalSummary.validateJsonElement(jsonObj.get("retrievalDetails"));
      }
      if (jsonObj.get("chargebackDetails") != null && !jsonObj.get("chargebackDetails").isJsonNull()) {
        JsonArray jsonArraychargebackDetails = jsonObj.getAsJsonArray("chargebackDetails");
        if (jsonArraychargebackDetails != null) {
          // ensure the json data is an array
          if (!jsonObj.get("chargebackDetails").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `chargebackDetails` to be an array in the JSON string but got `%s`", jsonObj.get("chargebackDetails").toString()));
          }

          // validate the optional field `chargebackDetails` (array)
          for (int i = 0; i < jsonArraychargebackDetails.size(); i++) {
            ChargebackDetails.validateJsonElement(jsonArraychargebackDetails.get(i));
          };
        }
      }
      if (jsonObj.get("feeDetails") != null && !jsonObj.get("feeDetails").isJsonNull()) {
        JsonArray jsonArrayfeeDetails = jsonObj.getAsJsonArray("feeDetails");
        if (jsonArrayfeeDetails != null) {
          // ensure the json data is an array
          if (!jsonObj.get("feeDetails").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `feeDetails` to be an array in the JSON string but got `%s`", jsonObj.get("feeDetails").toString()));
          }

          // validate the optional field `feeDetails` (array)
          for (int i = 0; i < jsonArrayfeeDetails.size(); i++) {
            FeeDetails.validateJsonElement(jsonArrayfeeDetails.get(i));
          };
        }
      }
      if (jsonObj.get("retrievalDetailsList") != null && !jsonObj.get("retrievalDetailsList").isJsonNull()) {
        JsonArray jsonArrayretrievalDetailsList = jsonObj.getAsJsonArray("retrievalDetailsList");
        if (jsonArrayretrievalDetailsList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("retrievalDetailsList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `retrievalDetailsList` to be an array in the JSON string but got `%s`", jsonObj.get("retrievalDetailsList").toString()));
          }

          // validate the optional field `retrievalDetailsList` (array)
          for (int i = 0; i < jsonArrayretrievalDetailsList.size(); i++) {
            RetrievalSummary.validateJsonElement(jsonArrayretrievalDetailsList.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ClaimDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ClaimDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ClaimDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ClaimDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<ClaimDetail>() {
           @Override
           public void write(JsonWriter out, ClaimDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ClaimDetail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ClaimDetail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ClaimDetail
  * @throws IOException if the JSON string is invalid with respect to ClaimDetail
  */
  public static ClaimDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ClaimDetail.class);
  }

 /**
  * Convert an instance of ClaimDetail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

