/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import java.util.Objects;
import bp4.mastercom_api_client.model.ChargebackAmountNameValueDetail;
import bp4.mastercom_api_client.model.ChargebackDocIndicatorsNameValueDetail;
import bp4.mastercom_api_client.model.ChargebackMessageTextsNameValueDetail;
import bp4.mastercom_api_client.model.ChargebackReasonCodesNameValueDetail;
import bp4.mastercom_api_client.model.CurrenciesNameValueDetail;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import bp4.mastercom_api_client.JSON;

/**
 * LoadDataForChargebackResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T19:57:39.604201-03:00[America/Buenos_Aires]")
public class LoadDataForChargebackResponse {
  public static final String SERIALIZED_NAME_CURRENCIES = "currencies";
  @SerializedName(SERIALIZED_NAME_CURRENCIES)
  private List<CurrenciesNameValueDetail> currencies;

  public static final String SERIALIZED_NAME_DOC_INDICATORS = "docIndicators";
  @SerializedName(SERIALIZED_NAME_DOC_INDICATORS)
  private List<ChargebackDocIndicatorsNameValueDetail> docIndicators;

  public static final String SERIALIZED_NAME_MESSAGE_TEXTS = "messageTexts";
  @SerializedName(SERIALIZED_NAME_MESSAGE_TEXTS)
  private List<ChargebackMessageTextsNameValueDetail> messageTexts;

  public static final String SERIALIZED_NAME_REASON_CODES = "reasonCodes";
  @SerializedName(SERIALIZED_NAME_REASON_CODES)
  private List<ChargebackReasonCodesNameValueDetail> reasonCodes;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private ChargebackAmountNameValueDetail amount;

  public LoadDataForChargebackResponse() {
  }

  public LoadDataForChargebackResponse currencies(List<CurrenciesNameValueDetail> currencies) {
    
    this.currencies = currencies;
    return this;
  }

  public LoadDataForChargebackResponse addCurrenciesItem(CurrenciesNameValueDetail currenciesItem) {
    if (this.currencies == null) {
      this.currencies = new ArrayList<>();
    }
    this.currencies.add(currenciesItem);
    return this;
  }

   /**
   * List of valid currencies
   * @return currencies
  **/
  @javax.annotation.Nullable
  public List<CurrenciesNameValueDetail> getCurrencies() {
    return currencies;
  }


  public void setCurrencies(List<CurrenciesNameValueDetail> currencies) {
    this.currencies = currencies;
  }


  public LoadDataForChargebackResponse docIndicators(List<ChargebackDocIndicatorsNameValueDetail> docIndicators) {
    
    this.docIndicators = docIndicators;
    return this;
  }

  public LoadDataForChargebackResponse addDocIndicatorsItem(ChargebackDocIndicatorsNameValueDetail docIndicatorsItem) {
    if (this.docIndicators == null) {
      this.docIndicators = new ArrayList<>();
    }
    this.docIndicators.add(docIndicatorsItem);
    return this;
  }

   /**
   * List of valid doc indicators
   * @return docIndicators
  **/
  @javax.annotation.Nullable
  public List<ChargebackDocIndicatorsNameValueDetail> getDocIndicators() {
    return docIndicators;
  }


  public void setDocIndicators(List<ChargebackDocIndicatorsNameValueDetail> docIndicators) {
    this.docIndicators = docIndicators;
  }


  public LoadDataForChargebackResponse messageTexts(List<ChargebackMessageTextsNameValueDetail> messageTexts) {
    
    this.messageTexts = messageTexts;
    return this;
  }

  public LoadDataForChargebackResponse addMessageTextsItem(ChargebackMessageTextsNameValueDetail messageTextsItem) {
    if (this.messageTexts == null) {
      this.messageTexts = new ArrayList<>();
    }
    this.messageTexts.add(messageTextsItem);
    return this;
  }

   /**
   * List of valid message texts
   * @return messageTexts
  **/
  @javax.annotation.Nullable
  public List<ChargebackMessageTextsNameValueDetail> getMessageTexts() {
    return messageTexts;
  }


  public void setMessageTexts(List<ChargebackMessageTextsNameValueDetail> messageTexts) {
    this.messageTexts = messageTexts;
  }


  public LoadDataForChargebackResponse reasonCodes(List<ChargebackReasonCodesNameValueDetail> reasonCodes) {
    
    this.reasonCodes = reasonCodes;
    return this;
  }

  public LoadDataForChargebackResponse addReasonCodesItem(ChargebackReasonCodesNameValueDetail reasonCodesItem) {
    if (this.reasonCodes == null) {
      this.reasonCodes = new ArrayList<>();
    }
    this.reasonCodes.add(reasonCodesItem);
    return this;
  }

   /**
   * List of valid reason codes
   * @return reasonCodes
  **/
  @javax.annotation.Nullable
  public List<ChargebackReasonCodesNameValueDetail> getReasonCodes() {
    return reasonCodes;
  }


  public void setReasonCodes(List<ChargebackReasonCodesNameValueDetail> reasonCodes) {
    this.reasonCodes = reasonCodes;
  }


  public LoadDataForChargebackResponse amount(ChargebackAmountNameValueDetail amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  public ChargebackAmountNameValueDetail getAmount() {
    return amount;
  }


  public void setAmount(ChargebackAmountNameValueDetail amount) {
    this.amount = amount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoadDataForChargebackResponse loadDataForChargebackResponse = (LoadDataForChargebackResponse) o;
    return Objects.equals(this.currencies, loadDataForChargebackResponse.currencies) &&
        Objects.equals(this.docIndicators, loadDataForChargebackResponse.docIndicators) &&
        Objects.equals(this.messageTexts, loadDataForChargebackResponse.messageTexts) &&
        Objects.equals(this.reasonCodes, loadDataForChargebackResponse.reasonCodes) &&
        Objects.equals(this.amount, loadDataForChargebackResponse.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currencies, docIndicators, messageTexts, reasonCodes, amount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoadDataForChargebackResponse {\n");
    sb.append("    currencies: ").append(toIndentedString(currencies)).append("\n");
    sb.append("    docIndicators: ").append(toIndentedString(docIndicators)).append("\n");
    sb.append("    messageTexts: ").append(toIndentedString(messageTexts)).append("\n");
    sb.append("    reasonCodes: ").append(toIndentedString(reasonCodes)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("currencies");
    openapiFields.add("docIndicators");
    openapiFields.add("messageTexts");
    openapiFields.add("reasonCodes");
    openapiFields.add("amount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to LoadDataForChargebackResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LoadDataForChargebackResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LoadDataForChargebackResponse is not found in the empty JSON string", LoadDataForChargebackResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LoadDataForChargebackResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LoadDataForChargebackResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("currencies") != null && !jsonObj.get("currencies").isJsonNull()) {
        JsonArray jsonArraycurrencies = jsonObj.getAsJsonArray("currencies");
        if (jsonArraycurrencies != null) {
          // ensure the json data is an array
          if (!jsonObj.get("currencies").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `currencies` to be an array in the JSON string but got `%s`", jsonObj.get("currencies").toString()));
          }

          // validate the optional field `currencies` (array)
          for (int i = 0; i < jsonArraycurrencies.size(); i++) {
            CurrenciesNameValueDetail.validateJsonElement(jsonArraycurrencies.get(i));
          };
        }
      }
      if (jsonObj.get("docIndicators") != null && !jsonObj.get("docIndicators").isJsonNull()) {
        JsonArray jsonArraydocIndicators = jsonObj.getAsJsonArray("docIndicators");
        if (jsonArraydocIndicators != null) {
          // ensure the json data is an array
          if (!jsonObj.get("docIndicators").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `docIndicators` to be an array in the JSON string but got `%s`", jsonObj.get("docIndicators").toString()));
          }

          // validate the optional field `docIndicators` (array)
          for (int i = 0; i < jsonArraydocIndicators.size(); i++) {
            ChargebackDocIndicatorsNameValueDetail.validateJsonElement(jsonArraydocIndicators.get(i));
          };
        }
      }
      if (jsonObj.get("messageTexts") != null && !jsonObj.get("messageTexts").isJsonNull()) {
        JsonArray jsonArraymessageTexts = jsonObj.getAsJsonArray("messageTexts");
        if (jsonArraymessageTexts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("messageTexts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `messageTexts` to be an array in the JSON string but got `%s`", jsonObj.get("messageTexts").toString()));
          }

          // validate the optional field `messageTexts` (array)
          for (int i = 0; i < jsonArraymessageTexts.size(); i++) {
            ChargebackMessageTextsNameValueDetail.validateJsonElement(jsonArraymessageTexts.get(i));
          };
        }
      }
      if (jsonObj.get("reasonCodes") != null && !jsonObj.get("reasonCodes").isJsonNull()) {
        JsonArray jsonArrayreasonCodes = jsonObj.getAsJsonArray("reasonCodes");
        if (jsonArrayreasonCodes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("reasonCodes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `reasonCodes` to be an array in the JSON string but got `%s`", jsonObj.get("reasonCodes").toString()));
          }

          // validate the optional field `reasonCodes` (array)
          for (int i = 0; i < jsonArrayreasonCodes.size(); i++) {
            ChargebackReasonCodesNameValueDetail.validateJsonElement(jsonArrayreasonCodes.get(i));
          };
        }
      }
      // validate the optional field `amount`
      if (jsonObj.get("amount") != null && !jsonObj.get("amount").isJsonNull()) {
        ChargebackAmountNameValueDetail.validateJsonElement(jsonObj.get("amount"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoadDataForChargebackResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoadDataForChargebackResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoadDataForChargebackResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoadDataForChargebackResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<LoadDataForChargebackResponse>() {
           @Override
           public void write(JsonWriter out, LoadDataForChargebackResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LoadDataForChargebackResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LoadDataForChargebackResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LoadDataForChargebackResponse
  * @throws IOException if the JSON string is invalid with respect to LoadDataForChargebackResponse
  */
  public static LoadDataForChargebackResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoadDataForChargebackResponse.class);
  }

 /**
  * Convert an instance of LoadDataForChargebackResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

