/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import java.util.Objects;
import bp4.mastercom_api_client.model.RetrievalStatusRequestStructure;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import bp4.mastercom_api_client.JSON;

/**
 * RetrievalStatusRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T19:57:39.604201-03:00[America/Buenos_Aires]")
public class RetrievalStatusRequest {
  public static final String SERIALIZED_NAME_RETRIEVAL_LIST = "retrievalList";
  @SerializedName(SERIALIZED_NAME_RETRIEVAL_LIST)
  private List<RetrievalStatusRequestStructure> retrievalList = new ArrayList<>();

  public RetrievalStatusRequest() {
  }

  public RetrievalStatusRequest retrievalList(List<RetrievalStatusRequestStructure> retrievalList) {
    
    this.retrievalList = retrievalList;
    return this;
  }

  public RetrievalStatusRequest addRetrievalListItem(RetrievalStatusRequestStructure retrievalListItem) {
    if (this.retrievalList == null) {
      this.retrievalList = new ArrayList<>();
    }
    this.retrievalList.add(retrievalListItem);
    return this;
  }

   /**
   * A list of Request Ids to query, maximum list size is 2000
   * @return retrievalList
  **/
  @javax.annotation.Nonnull
  public List<RetrievalStatusRequestStructure> getRetrievalList() {
    return retrievalList;
  }


  public void setRetrievalList(List<RetrievalStatusRequestStructure> retrievalList) {
    this.retrievalList = retrievalList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrievalStatusRequest retrievalStatusRequest = (RetrievalStatusRequest) o;
    return Objects.equals(this.retrievalList, retrievalStatusRequest.retrievalList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(retrievalList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrievalStatusRequest {\n");
    sb.append("    retrievalList: ").append(toIndentedString(retrievalList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("retrievalList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("retrievalList");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RetrievalStatusRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RetrievalStatusRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RetrievalStatusRequest is not found in the empty JSON string", RetrievalStatusRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RetrievalStatusRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RetrievalStatusRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RetrievalStatusRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("retrievalList").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `retrievalList` to be an array in the JSON string but got `%s`", jsonObj.get("retrievalList").toString()));
      }

      JsonArray jsonArrayretrievalList = jsonObj.getAsJsonArray("retrievalList");
      // validate the required field `retrievalList` (array)
      for (int i = 0; i < jsonArrayretrievalList.size(); i++) {
        RetrievalStatusRequestStructure.validateJsonElement(jsonArrayretrievalList.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RetrievalStatusRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RetrievalStatusRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RetrievalStatusRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RetrievalStatusRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<RetrievalStatusRequest>() {
           @Override
           public void write(JsonWriter out, RetrievalStatusRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RetrievalStatusRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RetrievalStatusRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RetrievalStatusRequest
  * @throws IOException if the JSON string is invalid with respect to RetrievalStatusRequest
  */
  public static RetrievalStatusRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RetrievalStatusRequest.class);
  }

 /**
  * Convert an instance of RetrievalStatusRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

