/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import java.util.Objects;
import bp4.mastercom_api_client.model.SingleMessageDetail;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import bp4.mastercom_api_client.JSON;

/**
 * TransactionSingleMessageDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T19:57:39.604201-03:00[America/Buenos_Aires]")
public class TransactionSingleMessageDetail {
  public static final String SERIALIZED_NAME_AUTH_TRANSACTION = "authTransaction";
  @SerializedName(SERIALIZED_NAME_AUTH_TRANSACTION)
  private SingleMessageDetail authTransaction;

  public static final String SERIALIZED_NAME_CLEARING_TRANSACTION = "clearingTransaction";
  @SerializedName(SERIALIZED_NAME_CLEARING_TRANSACTION)
  private SingleMessageDetail clearingTransaction;

  public TransactionSingleMessageDetail() {
  }

  public TransactionSingleMessageDetail authTransaction(SingleMessageDetail authTransaction) {
    
    this.authTransaction = authTransaction;
    return this;
  }

   /**
   * Get authTransaction
   * @return authTransaction
  **/
  @javax.annotation.Nullable
  public SingleMessageDetail getAuthTransaction() {
    return authTransaction;
  }


  public void setAuthTransaction(SingleMessageDetail authTransaction) {
    this.authTransaction = authTransaction;
  }


  public TransactionSingleMessageDetail clearingTransaction(SingleMessageDetail clearingTransaction) {
    
    this.clearingTransaction = clearingTransaction;
    return this;
  }

   /**
   * Get clearingTransaction
   * @return clearingTransaction
  **/
  @javax.annotation.Nullable
  public SingleMessageDetail getClearingTransaction() {
    return clearingTransaction;
  }


  public void setClearingTransaction(SingleMessageDetail clearingTransaction) {
    this.clearingTransaction = clearingTransaction;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionSingleMessageDetail transactionSingleMessageDetail = (TransactionSingleMessageDetail) o;
    return Objects.equals(this.authTransaction, transactionSingleMessageDetail.authTransaction) &&
        Objects.equals(this.clearingTransaction, transactionSingleMessageDetail.clearingTransaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authTransaction, clearingTransaction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionSingleMessageDetail {\n");
    sb.append("    authTransaction: ").append(toIndentedString(authTransaction)).append("\n");
    sb.append("    clearingTransaction: ").append(toIndentedString(clearingTransaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("authTransaction");
    openapiFields.add("clearingTransaction");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TransactionSingleMessageDetail
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TransactionSingleMessageDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TransactionSingleMessageDetail is not found in the empty JSON string", TransactionSingleMessageDetail.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TransactionSingleMessageDetail.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TransactionSingleMessageDetail` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `authTransaction`
      if (jsonObj.get("authTransaction") != null && !jsonObj.get("authTransaction").isJsonNull()) {
        SingleMessageDetail.validateJsonElement(jsonObj.get("authTransaction"));
      }
      // validate the optional field `clearingTransaction`
      if (jsonObj.get("clearingTransaction") != null && !jsonObj.get("clearingTransaction").isJsonNull()) {
        SingleMessageDetail.validateJsonElement(jsonObj.get("clearingTransaction"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransactionSingleMessageDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransactionSingleMessageDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransactionSingleMessageDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransactionSingleMessageDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<TransactionSingleMessageDetail>() {
           @Override
           public void write(JsonWriter out, TransactionSingleMessageDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TransactionSingleMessageDetail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TransactionSingleMessageDetail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TransactionSingleMessageDetail
  * @throws IOException if the JSON string is invalid with respect to TransactionSingleMessageDetail
  */
  public static TransactionSingleMessageDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransactionSingleMessageDetail.class);
  }

 /**
  * Convert an instance of TransactionSingleMessageDetail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

