/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CaseFilingResponse
 */
public class CaseFilingResponseTest {
    private final CaseFilingResponse model = new CaseFilingResponse();

    /**
     * Model tests for CaseFilingResponse
     */
    @Test
    public void testCaseFilingResponse() {
        // TODO: test CaseFilingResponse
    }

    /**
     * Test the property 'caseId'
     */
    @Test
    public void caseIdTest() {
        // TODO: test caseId
    }

}
