/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateClaimRequest
 */
public class CreateClaimRequestTest {
    private final CreateClaimRequest model = new CreateClaimRequest();

    /**
     * Model tests for CreateClaimRequest
     */
    @Test
    public void testCreateClaimRequest() {
        // TODO: test CreateClaimRequest
    }

    /**
     * Test the property 'disputedAmount'
     */
    @Test
    public void disputedAmountTest() {
        // TODO: test disputedAmount
    }

    /**
     * Test the property 'disputedCurrency'
     */
    @Test
    public void disputedCurrencyTest() {
        // TODO: test disputedCurrency
    }

    /**
     * Test the property 'claimType'
     */
    @Test
    public void claimTypeTest() {
        // TODO: test claimType
    }

    /**
     * Test the property 'clearingTransactionId'
     */
    @Test
    public void clearingTransactionIdTest() {
        // TODO: test clearingTransactionId
    }

    /**
     * Test the property 'authTransactionId'
     */
    @Test
    public void authTransactionIdTest() {
        // TODO: test authTransactionId
    }

}
