/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateRetrievalRequestSingle
 */
public class CreateRetrievalRequestSingleTest {
    private final CreateRetrievalRequestSingle model = new CreateRetrievalRequestSingle();

    /**
     * Model tests for CreateRetrievalRequestSingle
     */
    @Test
    public void testCreateRetrievalRequestSingle() {
        // TODO: test CreateRetrievalRequestSingle
    }

    /**
     * Test the property 'documentType'
     */
    @Test
    public void documentTypeTest() {
        // TODO: test documentType
    }

    /**
     * Test the property 'replacementAmount'
     */
    @Test
    public void replacementAmountTest() {
        // TODO: test replacementAmount
    }

    /**
     * Test the property 'reversalReasonCode'
     */
    @Test
    public void reversalReasonCodeTest() {
        // TODO: test reversalReasonCode
    }

    /**
     * Test the property 'usageCode'
     */
    @Test
    public void usageCodeTest() {
        // TODO: test usageCode
    }

    /**
     * Test the property 'additionalInformation'
     */
    @Test
    public void additionalInformationTest() {
        // TODO: test additionalInformation
    }

    /**
     * Test the property 'controlNumber'
     */
    @Test
    public void controlNumberTest() {
        // TODO: test controlNumber
    }

}
