/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateChargebackSingleReversalRequest
 */
public class CreateChargebackSingleReversalRequestTest {
    private final CreateChargebackSingleReversalRequest model = new CreateChargebackSingleReversalRequest();

    /**
     * Model tests for CreateChargebackSingleReversalRequest
     */
    @Test
    public void testCreateChargebackSingleReversalRequest() {
        // TODO: test CreateChargebackSingleReversalRequest
    }

    /**
     * Test the property 'replacementAmount'
     */
    @Test
    public void replacementAmountTest() {
        // TODO: test replacementAmount
    }

    /**
     * Test the property 'reversalReasonCode'
     */
    @Test
    public void reversalReasonCodeTest() {
        // TODO: test reversalReasonCode
    }

    /**
     * Test the property 'controlNumber'
     */
    @Test
    public void controlNumberTest() {
        // TODO: test controlNumber
    }

}
