/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for FeeSingleResponse
 */
public class FeeSingleResponseTest {
    private final FeeSingleResponse model = new FeeSingleResponse();

    /**
     * Model tests for FeeSingleResponse
     */
    @Test
    public void testFeeSingleResponse() {
        // TODO: test FeeSingleResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
