/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for FraudDrfDocumentStructure
 */
public class FraudDrfDocumentStructureTest {
    private final FraudDrfDocumentStructure model = new FraudDrfDocumentStructure();

    /**
     * Model tests for FraudDrfDocumentStructure
     */
    @Test
    public void testFraudDrfDocumentStructure() {
        // TODO: test FraudDrfDocumentStructure
    }

    /**
     * Test the property 'numberOfItems'
     */
    @Test
    public void numberOfItemsTest() {
        // TODO: test numberOfItems
    }

    /**
     * Test the property 'types'
     */
    @Test
    public void typesTest() {
        // TODO: test types
    }

    /**
     * Test the property 'additionalInformation'
     */
    @Test
    public void additionalInformationTest() {
        // TODO: test additionalInformation
    }

    /**
     * Test the property 'chargebackRepresentative'
     */
    @Test
    public void chargebackRepresentativeTest() {
        // TODO: test chargebackRepresentative
    }

    /**
     * Test the property 'cardIssuerRegion'
     */
    @Test
    public void cardIssuerRegionTest() {
        // TODO: test cardIssuerRegion
    }

    /**
     * Test the property 'cardholderVerificationMethod'
     */
    @Test
    public void cardholderVerificationMethodTest() {
        // TODO: test cardholderVerificationMethod
    }

}
