/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for GetQueueContentRequest
 */
public class GetQueueContentRequestTest {
    private final GetQueueContentRequest model = new GetQueueContentRequest();

    /**
     * Model tests for GetQueueContentRequest
     */
    @Test
    public void testGetQueueContentRequest() {
        // TODO: test GetQueueContentRequest
    }

    /**
     * Test the property 'queueName'
     */
    @Test
    public void queueNameTest() {
        // TODO: test queueName
    }

    /**
     * Test the property 'lastModifiedDateFrom'
     */
    @Test
    public void lastModifiedDateFromTest() {
        // TODO: test lastModifiedDateFrom
    }

    /**
     * Test the property 'lastModifiedDateTo'
     */
    @Test
    public void lastModifiedDateToTest() {
        // TODO: test lastModifiedDateTo
    }

    /**
     * Test the property 'pageNb'
     */
    @Test
    public void pageNbTest() {
        // TODO: test pageNb
    }

}
