/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for LoadDataForChargebacksRequest
 */
public class LoadDataForChargebacksRequestTest {
    private final LoadDataForChargebacksRequest model = new LoadDataForChargebacksRequest();

    /**
     * Model tests for LoadDataForChargebacksRequest
     */
    @Test
    public void testLoadDataForChargebacksRequest() {
        // TODO: test LoadDataForChargebacksRequest
    }

    /**
     * Test the property 'chargebackType'
     */
    @Test
    public void chargebackTypeTest() {
        // TODO: test chargebackType
    }

    /**
     * Test the property 'reasonCode'
     */
    @Test
    public void reasonCodeTest() {
        // TODO: test reasonCode
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

}
