/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for QueueContentSummary
 */
public class QueueContentSummaryTest {
    private final QueueContentSummary model = new QueueContentSummary();

    /**
     * Model tests for QueueContentSummary
     */
    @Test
    public void testQueueContentSummary() {
        // TODO: test QueueContentSummary
    }

    /**
     * Test the property 'pageCount'
     */
    @Test
    public void pageCountTest() {
        // TODO: test pageCount
    }

    /**
     * Test the property 'claimList'
     */
    @Test
    public void claimListTest() {
        // TODO: test claimList
    }

}
