/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrievalReasonCodesNameValueDetail
 */
public class RetrievalReasonCodesNameValueDetailTest {
    private final RetrievalReasonCodesNameValueDetail model = new RetrievalReasonCodesNameValueDetail();

    /**
     * Model tests for RetrievalReasonCodesNameValueDetail
     */
    @Test
    public void testRetrievalReasonCodesNameValueDetail() {
        // TODO: test RetrievalReasonCodesNameValueDetail
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
