/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrievalsImageStatusResponse
 */
public class RetrievalsImageStatusResponseTest {
    private final RetrievalsImageStatusResponse model = new RetrievalsImageStatusResponse();

    /**
     * Model tests for RetrievalsImageStatusResponse
     */
    @Test
    public void testRetrievalsImageStatusResponse() {
        // TODO: test RetrievalsImageStatusResponse
    }

    /**
     * Test the property 'retrievalImageStatusList'
     */
    @Test
    public void retrievalImageStatusListTest() {
        // TODO: test retrievalImageStatusList
    }

}
