/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrievalStatusResponse
 */
public class RetrievalStatusResponseTest {
    private final RetrievalStatusResponse model = new RetrievalStatusResponse();

    /**
     * Model tests for RetrievalStatusResponse
     */
    @Test
    public void testRetrievalStatusResponse() {
        // TODO: test RetrievalStatusResponse
    }

    /**
     * Test the property 'retrievalResponseList'
     */
    @Test
    public void retrievalResponseListTest() {
        // TODO: test retrievalResponseList
    }

}
