/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrievalResponse
 */
public class RetrievalResponseTest {
    private final RetrievalResponse model = new RetrievalResponse();

    /**
     * Model tests for RetrievalResponse
     */
    @Test
    public void testRetrievalResponse() {
        // TODO: test RetrievalResponse
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

}
