/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for SingleMessageSummaryDetails
 */
public class SingleMessageSummaryDetailsTest {
    private final SingleMessageSummaryDetails model = new SingleMessageSummaryDetails();

    /**
     * Model tests for SingleMessageSummaryDetails
     */
    @Test
    public void testSingleMessageSummaryDetails() {
        // TODO: test SingleMessageSummaryDetails
    }

    /**
     * Test the property 'authTransaction'
     */
    @Test
    public void authTransactionTest() {
        // TODO: test authTransaction
    }

    /**
     * Test the property 'clearingTransaction'
     */
    @Test
    public void clearingTransactionTest() {
        // TODO: test clearingTransaction
    }

}
