/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fiserv.mastercom_api_client.JSON;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * CaseFilingImageStatusResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T19:57:39.604201-03:00[America/Buenos_Aires]")
public class CaseFilingImageStatusResponse {
  public static final String SERIALIZED_NAME_CASE_FILING_IMAGE_STATUS_LIST = "caseFilingImageStatusList";
  @SerializedName(SERIALIZED_NAME_CASE_FILING_IMAGE_STATUS_LIST)
  private List<CaseFilingImageStatusResponseStructure> caseFilingImageStatusList;

  public CaseFilingImageStatusResponse() {
  }

  public CaseFilingImageStatusResponse caseFilingImageStatusList(List<CaseFilingImageStatusResponseStructure> caseFilingImageStatusList) {
    
    this.caseFilingImageStatusList = caseFilingImageStatusList;
    return this;
  }

  public CaseFilingImageStatusResponse addCaseFilingImageStatusListItem(CaseFilingImageStatusResponseStructure caseFilingImageStatusListItem) {
    if (this.caseFilingImageStatusList == null) {
      this.caseFilingImageStatusList = new ArrayList<>();
    }
    this.caseFilingImageStatusList.add(caseFilingImageStatusListItem);
    return this;
  }

   /**
   * A list of case filing image statuses
   * @return caseFilingImageStatusList
  **/
  @javax.annotation.Nullable
  public List<CaseFilingImageStatusResponseStructure> getCaseFilingImageStatusList() {
    return caseFilingImageStatusList;
  }


  public void setCaseFilingImageStatusList(List<CaseFilingImageStatusResponseStructure> caseFilingImageStatusList) {
    this.caseFilingImageStatusList = caseFilingImageStatusList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseFilingImageStatusResponse caseFilingImageStatusResponse = (CaseFilingImageStatusResponse) o;
    return Objects.equals(this.caseFilingImageStatusList, caseFilingImageStatusResponse.caseFilingImageStatusList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caseFilingImageStatusList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseFilingImageStatusResponse {\n");
    sb.append("    caseFilingImageStatusList: ").append(toIndentedString(caseFilingImageStatusList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("caseFilingImageStatusList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CaseFilingImageStatusResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CaseFilingImageStatusResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CaseFilingImageStatusResponse is not found in the empty JSON string", CaseFilingImageStatusResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CaseFilingImageStatusResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CaseFilingImageStatusResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("caseFilingImageStatusList") != null && !jsonObj.get("caseFilingImageStatusList").isJsonNull()) {
        JsonArray jsonArraycaseFilingImageStatusList = jsonObj.getAsJsonArray("caseFilingImageStatusList");
        if (jsonArraycaseFilingImageStatusList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("caseFilingImageStatusList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `caseFilingImageStatusList` to be an array in the JSON string but got `%s`", jsonObj.get("caseFilingImageStatusList").toString()));
          }

          // validate the optional field `caseFilingImageStatusList` (array)
          for (int i = 0; i < jsonArraycaseFilingImageStatusList.size(); i++) {
            CaseFilingImageStatusResponseStructure.validateJsonElement(jsonArraycaseFilingImageStatusList.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CaseFilingImageStatusResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CaseFilingImageStatusResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CaseFilingImageStatusResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CaseFilingImageStatusResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CaseFilingImageStatusResponse>() {
           @Override
           public void write(JsonWriter out, CaseFilingImageStatusResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CaseFilingImageStatusResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CaseFilingImageStatusResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CaseFilingImageStatusResponse
  * @throws IOException if the JSON string is invalid with respect to CaseFilingImageStatusResponse
  */
  public static CaseFilingImageStatusResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CaseFilingImageStatusResponse.class);
  }

 /**
  * Convert an instance of CaseFilingImageStatusResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

