/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fiserv.mastercom_api_client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * ChargebackMarkProcessedResponseStructure
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T19:57:39.604201-03:00[America/Buenos_Aires]")
public class ChargebackMarkProcessedResponseStructure {
  public static final String SERIALIZED_NAME_CHARGEBACK_ID = "chargebackId";
  @SerializedName(SERIALIZED_NAME_CHARGEBACK_ID)
  private String chargebackId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_FAILURE_REASON = "failureReason";
  @SerializedName(SERIALIZED_NAME_FAILURE_REASON)
  private String failureReason;

  public ChargebackMarkProcessedResponseStructure() {
  }

  public ChargebackMarkProcessedResponseStructure chargebackId(String chargebackId) {
    
    this.chargebackId = chargebackId;
    return this;
  }

   /**
   * Chargeback Id marked as processed
   * @return chargebackId
  **/
  @javax.annotation.Nullable
  public String getChargebackId() {
    return chargebackId;
  }


  public void setChargebackId(String chargebackId) {
    this.chargebackId = chargebackId;
  }


  public ChargebackMarkProcessedResponseStructure status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The status of the chargeback processing.
   * @return status
  **/
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public ChargebackMarkProcessedResponseStructure failureReason(String failureReason) {
    
    this.failureReason = failureReason;
    return this;
  }

   /**
   * The failure reason of the chargeback processing
   * @return failureReason
  **/
  @javax.annotation.Nullable
  public String getFailureReason() {
    return failureReason;
  }


  public void setFailureReason(String failureReason) {
    this.failureReason = failureReason;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargebackMarkProcessedResponseStructure chargebackMarkProcessedResponseStructure = (ChargebackMarkProcessedResponseStructure) o;
    return Objects.equals(this.chargebackId, chargebackMarkProcessedResponseStructure.chargebackId) &&
        Objects.equals(this.status, chargebackMarkProcessedResponseStructure.status) &&
        Objects.equals(this.failureReason, chargebackMarkProcessedResponseStructure.failureReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chargebackId, status, failureReason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargebackMarkProcessedResponseStructure {\n");
    sb.append("    chargebackId: ").append(toIndentedString(chargebackId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    failureReason: ").append(toIndentedString(failureReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("chargebackId");
    openapiFields.add("status");
    openapiFields.add("failureReason");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ChargebackMarkProcessedResponseStructure
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChargebackMarkProcessedResponseStructure.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChargebackMarkProcessedResponseStructure is not found in the empty JSON string", ChargebackMarkProcessedResponseStructure.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChargebackMarkProcessedResponseStructure.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChargebackMarkProcessedResponseStructure` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("chargebackId") != null && !jsonObj.get("chargebackId").isJsonNull()) && !jsonObj.get("chargebackId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chargebackId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chargebackId").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("failureReason") != null && !jsonObj.get("failureReason").isJsonNull()) && !jsonObj.get("failureReason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `failureReason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("failureReason").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChargebackMarkProcessedResponseStructure.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChargebackMarkProcessedResponseStructure' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChargebackMarkProcessedResponseStructure> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChargebackMarkProcessedResponseStructure.class));

       return (TypeAdapter<T>) new TypeAdapter<ChargebackMarkProcessedResponseStructure>() {
           @Override
           public void write(JsonWriter out, ChargebackMarkProcessedResponseStructure value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChargebackMarkProcessedResponseStructure read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ChargebackMarkProcessedResponseStructure given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ChargebackMarkProcessedResponseStructure
  * @throws IOException if the JSON string is invalid with respect to ChargebackMarkProcessedResponseStructure
  */
  public static ChargebackMarkProcessedResponseStructure fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChargebackMarkProcessedResponseStructure.class);
  }

 /**
  * Convert an instance of ChargebackMarkProcessedResponseStructure to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

