/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fiserv.mastercom_api_client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * OriginalInformationInstallments
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T19:57:39.604201-03:00[America/Buenos_Aires]")
public class OriginalInformationInstallments {
  public static final String SERIALIZED_NAME_AMOUNT_OF_PURCHASE = "amountOfPurchase";
  @SerializedName(SERIALIZED_NAME_AMOUNT_OF_PURCHASE)
  private String amountOfPurchase;

  public static final String SERIALIZED_NAME_TRANSACTION_INTEREST_RATE = "transactionInterestRate";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_INTEREST_RATE)
  private String transactionInterestRate;

  public static final String SERIALIZED_NAME_INSTALLMENT_AMOUNT = "installmentAmount";
  @SerializedName(SERIALIZED_NAME_INSTALLMENT_AMOUNT)
  private String installmentAmount;

  public OriginalInformationInstallments() {
  }

  public OriginalInformationInstallments amountOfPurchase(String amountOfPurchase) {
    
    this.amountOfPurchase = amountOfPurchase;
    return this;
  }

   /**
   * Amount of original purchase
   * @return amountOfPurchase
  **/
  @javax.annotation.Nullable
  public String getAmountOfPurchase() {
    return amountOfPurchase;
  }


  public void setAmountOfPurchase(String amountOfPurchase) {
    this.amountOfPurchase = amountOfPurchase;
  }


  public OriginalInformationInstallments transactionInterestRate(String transactionInterestRate) {
    
    this.transactionInterestRate = transactionInterestRate;
    return this;
  }

   /**
   * Percent rate for transaction
   * @return transactionInterestRate
  **/
  @javax.annotation.Nullable
  public String getTransactionInterestRate() {
    return transactionInterestRate;
  }


  public void setTransactionInterestRate(String transactionInterestRate) {
    this.transactionInterestRate = transactionInterestRate;
  }


  public OriginalInformationInstallments installmentAmount(String installmentAmount) {
    
    this.installmentAmount = installmentAmount;
    return this;
  }

   /**
   * Monthly amount for transaction
   * @return installmentAmount
  **/
  @javax.annotation.Nullable
  public String getInstallmentAmount() {
    return installmentAmount;
  }


  public void setInstallmentAmount(String installmentAmount) {
    this.installmentAmount = installmentAmount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OriginalInformationInstallments originalInformationInstallments = (OriginalInformationInstallments) o;
    return Objects.equals(this.amountOfPurchase, originalInformationInstallments.amountOfPurchase) &&
        Objects.equals(this.transactionInterestRate, originalInformationInstallments.transactionInterestRate) &&
        Objects.equals(this.installmentAmount, originalInformationInstallments.installmentAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountOfPurchase, transactionInterestRate, installmentAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OriginalInformationInstallments {\n");
    sb.append("    amountOfPurchase: ").append(toIndentedString(amountOfPurchase)).append("\n");
    sb.append("    transactionInterestRate: ").append(toIndentedString(transactionInterestRate)).append("\n");
    sb.append("    installmentAmount: ").append(toIndentedString(installmentAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("amountOfPurchase");
    openapiFields.add("transactionInterestRate");
    openapiFields.add("installmentAmount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OriginalInformationInstallments
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OriginalInformationInstallments.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OriginalInformationInstallments is not found in the empty JSON string", OriginalInformationInstallments.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OriginalInformationInstallments.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OriginalInformationInstallments` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("amountOfPurchase") != null && !jsonObj.get("amountOfPurchase").isJsonNull()) && !jsonObj.get("amountOfPurchase").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amountOfPurchase` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amountOfPurchase").toString()));
      }
      if ((jsonObj.get("transactionInterestRate") != null && !jsonObj.get("transactionInterestRate").isJsonNull()) && !jsonObj.get("transactionInterestRate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionInterestRate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionInterestRate").toString()));
      }
      if ((jsonObj.get("installmentAmount") != null && !jsonObj.get("installmentAmount").isJsonNull()) && !jsonObj.get("installmentAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `installmentAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("installmentAmount").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OriginalInformationInstallments.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OriginalInformationInstallments' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OriginalInformationInstallments> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OriginalInformationInstallments.class));

       return (TypeAdapter<T>) new TypeAdapter<OriginalInformationInstallments>() {
           @Override
           public void write(JsonWriter out, OriginalInformationInstallments value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OriginalInformationInstallments read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OriginalInformationInstallments given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OriginalInformationInstallments
  * @throws IOException if the JSON string is invalid with respect to OriginalInformationInstallments
  */
  public static OriginalInformationInstallments fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OriginalInformationInstallments.class);
  }

 /**
  * Convert an instance of OriginalInformationInstallments to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

