/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fiserv.mastercom_api_client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * PointOfInteractionErrorsDrfDocumentStructure
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T19:57:39.604201-03:00[America/Buenos_Aires]")
public class PointOfInteractionErrorsDrfDocumentStructure {
  public static final String SERIALIZED_NAME_TRANSACTION_AMOUNT = "transactionAmount";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_AMOUNT)
  private String transactionAmount;

  /**
   * The type of the error.   Length: 15-27   Valid Values/Format: DUPLICATE_DEBIT, INCORRECT_AMOUNT, LTD_TRANSACTION, CURRENCY_DISPUTE, UNREASONABLE_AMOUNT, DUPLICATE_TRANSACTION, MERCHANT_CREDIT, IMPROPER_MERCHANT_SURCHARGE
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    DUPLICATE_DEBIT("DUPLICATE_DEBIT"),
    
    INCORRECT_AMOUNT("INCORRECT_AMOUNT"),
    
    LTD_TRANSACTION("LTD_TRANSACTION"),
    
    CURRENCY_DISPUTE("CURRENCY_DISPUTE"),
    
    UNREASONABLE_AMOUNT("UNREASONABLE_AMOUNT"),
    
    DUPLICATE_TRANSACTION("DUPLICATE_TRANSACTION"),
    
    MERCHANT_CREDIT("MERCHANT_CREDIT"),
    
    IMPROPER_MERCHANT_SURCHARGE("IMPROPER_MERCHANT_SURCHARGE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_ALTERNATE_MEANS_OF_PAYMENT_DETAILS = "alternateMeansOfPaymentDetails";
  @SerializedName(SERIALIZED_NAME_ALTERNATE_MEANS_OF_PAYMENT_DETAILS)
  private String alternateMeansOfPaymentDetails;

  public static final String SERIALIZED_NAME_DISPUTE_DETAILS = "disputeDetails";
  @SerializedName(SERIALIZED_NAME_DISPUTE_DETAILS)
  private String disputeDetails;

  public static final String SERIALIZED_NAME_CHARGEBACK_REPRESENTATIVE = "chargebackRepresentative";
  @SerializedName(SERIALIZED_NAME_CHARGEBACK_REPRESENTATIVE)
  private String chargebackRepresentative;

  public PointOfInteractionErrorsDrfDocumentStructure() {
  }

  public PointOfInteractionErrorsDrfDocumentStructure transactionAmount(String transactionAmount) {
    
    this.transactionAmount = transactionAmount;
    return this;
  }

   /**
   * The transaction amount.   Length: 0-12   Valid Values/Format: Numeric
   * @return transactionAmount
  **/
  @javax.annotation.Nullable
  public String getTransactionAmount() {
    return transactionAmount;
  }


  public void setTransactionAmount(String transactionAmount) {
    this.transactionAmount = transactionAmount;
  }


  public PointOfInteractionErrorsDrfDocumentStructure type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of the error.   Length: 15-27   Valid Values/Format: DUPLICATE_DEBIT, INCORRECT_AMOUNT, LTD_TRANSACTION, CURRENCY_DISPUTE, UNREASONABLE_AMOUNT, DUPLICATE_TRANSACTION, MERCHANT_CREDIT, IMPROPER_MERCHANT_SURCHARGE
   * @return type
  **/
  @javax.annotation.Nullable
  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public PointOfInteractionErrorsDrfDocumentStructure alternateMeansOfPaymentDetails(String alternateMeansOfPaymentDetails) {
    
    this.alternateMeansOfPaymentDetails = alternateMeansOfPaymentDetails;
    return this;
  }

   /**
   * CONDITIONAL: in case of DUPLICATE_DEBIT, Alternate means of payment details.   Length: 0-55   Valid Values/Format: Alphanumeric / Special Char (~!@#$%^&amp;*()_+{}|:\&quot;&lt;&gt;?,./;&#39;[]-&#x3D;)
   * @return alternateMeansOfPaymentDetails
  **/
  @javax.annotation.Nullable
  public String getAlternateMeansOfPaymentDetails() {
    return alternateMeansOfPaymentDetails;
  }


  public void setAlternateMeansOfPaymentDetails(String alternateMeansOfPaymentDetails) {
    this.alternateMeansOfPaymentDetails = alternateMeansOfPaymentDetails;
  }


  public PointOfInteractionErrorsDrfDocumentStructure disputeDetails(String disputeDetails) {
    
    this.disputeDetails = disputeDetails;
    return this;
  }

   /**
   * Describe the cardholder’s compliant in sufficient detail to meet the requirements for the chargeback as described in the Chargeback Guide and to enable all parties to understand the dispute.   Length: 0-4800   Valid Values/Format: Alphanumeric / Special Char (~!@#$%^&amp;*()_+{}|:\&quot;&lt;&gt;?,./;&#39;[]-&#x3D;)
   * @return disputeDetails
  **/
  @javax.annotation.Nullable
  public String getDisputeDetails() {
    return disputeDetails;
  }


  public void setDisputeDetails(String disputeDetails) {
    this.disputeDetails = disputeDetails;
  }


  public PointOfInteractionErrorsDrfDocumentStructure chargebackRepresentative(String chargebackRepresentative) {
    
    this.chargebackRepresentative = chargebackRepresentative;
    return this;
  }

   /**
   * Customer Service/Chargeback Representative.   Length: 0-25   Valid Values/Format: Alphanumeric / Special Char (~!@#$%^&amp;*()_+{}|:\&quot;&lt;&gt;?,./;&#39;[]-&#x3D;)
   * @return chargebackRepresentative
  **/
  @javax.annotation.Nullable
  public String getChargebackRepresentative() {
    return chargebackRepresentative;
  }


  public void setChargebackRepresentative(String chargebackRepresentative) {
    this.chargebackRepresentative = chargebackRepresentative;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PointOfInteractionErrorsDrfDocumentStructure pointOfInteractionErrorsDrfDocumentStructure = (PointOfInteractionErrorsDrfDocumentStructure) o;
    return Objects.equals(this.transactionAmount, pointOfInteractionErrorsDrfDocumentStructure.transactionAmount) &&
        Objects.equals(this.type, pointOfInteractionErrorsDrfDocumentStructure.type) &&
        Objects.equals(this.alternateMeansOfPaymentDetails, pointOfInteractionErrorsDrfDocumentStructure.alternateMeansOfPaymentDetails) &&
        Objects.equals(this.disputeDetails, pointOfInteractionErrorsDrfDocumentStructure.disputeDetails) &&
        Objects.equals(this.chargebackRepresentative, pointOfInteractionErrorsDrfDocumentStructure.chargebackRepresentative);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionAmount, type, alternateMeansOfPaymentDetails, disputeDetails, chargebackRepresentative);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PointOfInteractionErrorsDrfDocumentStructure {\n");
    sb.append("    transactionAmount: ").append(toIndentedString(transactionAmount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    alternateMeansOfPaymentDetails: ").append(toIndentedString(alternateMeansOfPaymentDetails)).append("\n");
    sb.append("    disputeDetails: ").append(toIndentedString(disputeDetails)).append("\n");
    sb.append("    chargebackRepresentative: ").append(toIndentedString(chargebackRepresentative)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("transactionAmount");
    openapiFields.add("type");
    openapiFields.add("alternateMeansOfPaymentDetails");
    openapiFields.add("disputeDetails");
    openapiFields.add("chargebackRepresentative");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PointOfInteractionErrorsDrfDocumentStructure
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PointOfInteractionErrorsDrfDocumentStructure.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PointOfInteractionErrorsDrfDocumentStructure is not found in the empty JSON string", PointOfInteractionErrorsDrfDocumentStructure.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PointOfInteractionErrorsDrfDocumentStructure.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PointOfInteractionErrorsDrfDocumentStructure` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("transactionAmount") != null && !jsonObj.get("transactionAmount").isJsonNull()) && !jsonObj.get("transactionAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionAmount").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("alternateMeansOfPaymentDetails") != null && !jsonObj.get("alternateMeansOfPaymentDetails").isJsonNull()) && !jsonObj.get("alternateMeansOfPaymentDetails").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `alternateMeansOfPaymentDetails` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alternateMeansOfPaymentDetails").toString()));
      }
      if ((jsonObj.get("disputeDetails") != null && !jsonObj.get("disputeDetails").isJsonNull()) && !jsonObj.get("disputeDetails").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `disputeDetails` to be a primitive type in the JSON string but got `%s`", jsonObj.get("disputeDetails").toString()));
      }
      if ((jsonObj.get("chargebackRepresentative") != null && !jsonObj.get("chargebackRepresentative").isJsonNull()) && !jsonObj.get("chargebackRepresentative").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chargebackRepresentative` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chargebackRepresentative").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PointOfInteractionErrorsDrfDocumentStructure.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PointOfInteractionErrorsDrfDocumentStructure' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PointOfInteractionErrorsDrfDocumentStructure> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PointOfInteractionErrorsDrfDocumentStructure.class));

       return (TypeAdapter<T>) new TypeAdapter<PointOfInteractionErrorsDrfDocumentStructure>() {
           @Override
           public void write(JsonWriter out, PointOfInteractionErrorsDrfDocumentStructure value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PointOfInteractionErrorsDrfDocumentStructure read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PointOfInteractionErrorsDrfDocumentStructure given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PointOfInteractionErrorsDrfDocumentStructure
  * @throws IOException if the JSON string is invalid with respect to PointOfInteractionErrorsDrfDocumentStructure
  */
  public static PointOfInteractionErrorsDrfDocumentStructure fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PointOfInteractionErrorsDrfDocumentStructure.class);
  }

 /**
  * Convert an instance of PointOfInteractionErrorsDrfDocumentStructure to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

