/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fiserv.mastercom_api_client.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fiserv.mastercom_api_client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * ReconReportDataAcknowledgeResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T19:57:39.604201-03:00[America/Buenos_Aires]")
public class ReconReportDataAcknowledgeResponse {
  public static final String SERIALIZED_NAME_REPORT_IDENTIFIER = "reportIdentifier";
  @SerializedName(SERIALIZED_NAME_REPORT_IDENTIFIER)
  private String reportIdentifier;

  public ReconReportDataAcknowledgeResponse() {
  }

  public ReconReportDataAcknowledgeResponse reportIdentifier(String reportIdentifier) {
    
    this.reportIdentifier = reportIdentifier;
    return this;
  }

   /**
   * A 36 bit UUID identifier that identifies the current reconciliation report generation request.
   * @return reportIdentifier
  **/
  @javax.annotation.Nullable
  public String getReportIdentifier() {
    return reportIdentifier;
  }


  public void setReportIdentifier(String reportIdentifier) {
    this.reportIdentifier = reportIdentifier;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReconReportDataAcknowledgeResponse reconReportDataAcknowledgeResponse = (ReconReportDataAcknowledgeResponse) o;
    return Objects.equals(this.reportIdentifier, reconReportDataAcknowledgeResponse.reportIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportIdentifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReconReportDataAcknowledgeResponse {\n");
    sb.append("    reportIdentifier: ").append(toIndentedString(reportIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("reportIdentifier");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ReconReportDataAcknowledgeResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReconReportDataAcknowledgeResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReconReportDataAcknowledgeResponse is not found in the empty JSON string", ReconReportDataAcknowledgeResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ReconReportDataAcknowledgeResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ReconReportDataAcknowledgeResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("reportIdentifier") != null && !jsonObj.get("reportIdentifier").isJsonNull()) && !jsonObj.get("reportIdentifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reportIdentifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reportIdentifier").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReconReportDataAcknowledgeResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReconReportDataAcknowledgeResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReconReportDataAcknowledgeResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReconReportDataAcknowledgeResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ReconReportDataAcknowledgeResponse>() {
           @Override
           public void write(JsonWriter out, ReconReportDataAcknowledgeResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReconReportDataAcknowledgeResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReconReportDataAcknowledgeResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReconReportDataAcknowledgeResponse
  * @throws IOException if the JSON string is invalid with respect to ReconReportDataAcknowledgeResponse
  */
  public static ReconReportDataAcknowledgeResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReconReportDataAcknowledgeResponse.class);
  }

 /**
  * Convert an instance of ReconReportDataAcknowledgeResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

