/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthorizationDetail
 */
public class AuthorizationDetailTest {
    private final AuthorizationDetail model = new AuthorizationDetail();

    /**
     * Model tests for AuthorizationDetail
     */
    @Test
    public void testAuthorizationDetail() {
        // TODO: test AuthorizationDetail
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'accountNumberIndicator'
     */
    @Test
    public void accountNumberIndicatorTest() {
        // TODO: test accountNumberIndicator
    }

    /**
     * Test the property 'acquirer'
     */
    @Test
    public void acquirerTest() {
        // TODO: test acquirer
    }

    /**
     * Test the property 'acquiringInstitutionCountryCode'
     */
    @Test
    public void acquiringInstitutionCountryCodeTest() {
        // TODO: test acquiringInstitutionCountryCode
    }

    /**
     * Test the property 'acquiringInstitutionId'
     */
    @Test
    public void acquiringInstitutionIdTest() {
        // TODO: test acquiringInstitutionId
    }

    /**
     * Test the property 'addressVerificationServiceResponse'
     */
    @Test
    public void addressVerificationServiceResponseTest() {
        // TODO: test addressVerificationServiceResponse
    }

    /**
     * Test the property 'adviceReasonCode'
     */
    @Test
    public void adviceReasonCodeTest() {
        // TODO: test adviceReasonCode
    }

    /**
     * Test the property 'atcDiscrepancyIndicator'
     */
    @Test
    public void atcDiscrepancyIndicatorTest() {
        // TODO: test atcDiscrepancyIndicator
    }

    /**
     * Test the property 'atcDiscrepancyValue'
     */
    @Test
    public void atcDiscrepancyValueTest() {
        // TODO: test atcDiscrepancyValue
    }

    /**
     * Test the property 'atcValue'
     */
    @Test
    public void atcValueTest() {
        // TODO: test atcValue
    }

    /**
     * Test the property 'authenticationIndicator'
     */
    @Test
    public void authenticationIndicatorTest() {
        // TODO: test authenticationIndicator
    }

    /**
     * Test the property 'authorizationIdResponse'
     */
    @Test
    public void authorizationIdResponseTest() {
        // TODO: test authorizationIdResponse
    }

    /**
     * Test the property 'banknetDate'
     */
    @Test
    public void banknetDateTest() {
        // TODO: test banknetDate
    }

    /**
     * Test the property 'banknetReferenceNumber'
     */
    @Test
    public void banknetReferenceNumberTest() {
        // TODO: test banknetReferenceNumber
    }

    /**
     * Test the property 'billingCurrencyCode'
     */
    @Test
    public void billingCurrencyCodeTest() {
        // TODO: test billingCurrencyCode
    }

    /**
     * Test the property 'cardAcceptorCity'
     */
    @Test
    public void cardAcceptorCityTest() {
        // TODO: test cardAcceptorCity
    }

    /**
     * Test the property 'cardAcceptorId'
     */
    @Test
    public void cardAcceptorIdTest() {
        // TODO: test cardAcceptorId
    }

    /**
     * Test the property 'cardAcceptorName'
     */
    @Test
    public void cardAcceptorNameTest() {
        // TODO: test cardAcceptorName
    }

    /**
     * Test the property 'cardAcceptorState'
     */
    @Test
    public void cardAcceptorStateTest() {
        // TODO: test cardAcceptorState
    }

    /**
     * Test the property 'cardAcceptorTerminalId'
     */
    @Test
    public void cardAcceptorTerminalIdTest() {
        // TODO: test cardAcceptorTerminalId
    }

    /**
     * Test the property 'cardholderActivatedTerminalLevel'
     */
    @Test
    public void cardholderActivatedTerminalLevelTest() {
        // TODO: test cardholderActivatedTerminalLevel
    }

    /**
     * Test the property 'cardholderBillingActualAmount'
     */
    @Test
    public void cardholderBillingActualAmountTest() {
        // TODO: test cardholderBillingActualAmount
    }

    /**
     * Test the property 'cardholderBillingAmount'
     */
    @Test
    public void cardholderBillingAmountTest() {
        // TODO: test cardholderBillingAmount
    }

    /**
     * Test the property 'cardAuthenticationMethodValidationCode'
     */
    @Test
    public void cardAuthenticationMethodValidationCodeTest() {
        // TODO: test cardAuthenticationMethodValidationCode
    }

    /**
     * Test the property 'conversionDate'
     */
    @Test
    public void conversionDateTest() {
        // TODO: test conversionDate
    }

    /**
     * Test the property 'conversionRate'
     */
    @Test
    public void conversionRateTest() {
        // TODO: test conversionRate
    }

    /**
     * Test the property 'electronicCommerceIndicators'
     */
    @Test
    public void electronicCommerceIndicatorsTest() {
        // TODO: test electronicCommerceIndicators
    }

    /**
     * Test the property 'electronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicator'
     */
    @Test
    public void electronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicatorTest() {
        // TODO: test electronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicator
    }

    /**
     * Test the property 'expirationDatePresenceInd'
     */
    @Test
    public void expirationDatePresenceIndTest() {
        // TODO: test expirationDatePresenceInd
    }

    /**
     * Test the property 'finalAuthorizationIndicator'
     */
    @Test
    public void finalAuthorizationIndicatorTest() {
        // TODO: test finalAuthorizationIndicator
    }

    /**
     * Test the property 'financialNetworkCode'
     */
    @Test
    public void financialNetworkCodeTest() {
        // TODO: test financialNetworkCode
    }

    /**
     * Test the property 'forwardingInstitutionId'
     */
    @Test
    public void forwardingInstitutionIdTest() {
        // TODO: test forwardingInstitutionId
    }

    /**
     * Test the property 'infData'
     */
    @Test
    public void infDataTest() {
        // TODO: test infData
    }

    /**
     * Test the property 'integratedCircuitCardRelatedData'
     */
    @Test
    public void integratedCircuitCardRelatedDataTest() {
        // TODO: test integratedCircuitCardRelatedData
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'mastercardPromotionCode'
     */
    @Test
    public void mastercardPromotionCodeTest() {
        // TODO: test mastercardPromotionCode
    }

    /**
     * Test the property 'mccMessageId'
     */
    @Test
    public void mccMessageIdTest() {
        // TODO: test mccMessageId
    }

    /**
     * Test the property 'merchantAdviceCode'
     */
    @Test
    public void merchantAdviceCodeTest() {
        // TODO: test merchantAdviceCode
    }

    /**
     * Test the property 'merchantCategoryCode'
     */
    @Test
    public void merchantCategoryCodeTest() {
        // TODO: test merchantCategoryCode
    }

    /**
     * Test the property 'mobilePhoneNumber'
     */
    @Test
    public void mobilePhoneNumberTest() {
        // TODO: test mobilePhoneNumber
    }

    /**
     * Test the property 'mobilePhoneServiceProviderName'
     */
    @Test
    public void mobilePhoneServiceProviderNameTest() {
        // TODO: test mobilePhoneServiceProviderName
    }

    /**
     * Test the property 'originalAcquiringInstitutionIdCode'
     */
    @Test
    public void originalAcquiringInstitutionIdCodeTest() {
        // TODO: test originalAcquiringInstitutionIdCode
    }

    /**
     * Test the property 'originalElectronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicator'
     */
    @Test
    public void originalElectronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicatorTest() {
        // TODO: test originalElectronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicator
    }

    /**
     * Test the property 'originalIssuerForwardingInstitutionIdCode'
     */
    @Test
    public void originalIssuerForwardingInstitutionIdCodeTest() {
        // TODO: test originalIssuerForwardingInstitutionIdCode
    }

    /**
     * Test the property 'originalMessageTypeIdentifier'
     */
    @Test
    public void originalMessageTypeIdentifierTest() {
        // TODO: test originalMessageTypeIdentifier
    }

    /**
     * Test the property 'pinServiceCode'
     */
    @Test
    public void pinServiceCodeTest() {
        // TODO: test pinServiceCode
    }

    /**
     * Test the property 'realTimeSubstantiationIndicator'
     */
    @Test
    public void realTimeSubstantiationIndicatorTest() {
        // TODO: test realTimeSubstantiationIndicator
    }

    /**
     * Test the property 'reasonForUcafCollectionIndicatorDowngrade'
     */
    @Test
    public void reasonForUcafCollectionIndicatorDowngradeTest() {
        // TODO: test reasonForUcafCollectionIndicatorDowngrade
    }

    /**
     * Test the property 'posCardDataTerminalInputCapability'
     */
    @Test
    public void posCardDataTerminalInputCapabilityTest() {
        // TODO: test posCardDataTerminalInputCapability
    }

    /**
     * Test the property 'posCardholderPresence'
     */
    @Test
    public void posCardholderPresenceTest() {
        // TODO: test posCardholderPresence
    }

    /**
     * Test the property 'posCardPresence'
     */
    @Test
    public void posCardPresenceTest() {
        // TODO: test posCardPresence
    }

    /**
     * Test the property 'posEntryModePan'
     */
    @Test
    public void posEntryModePanTest() {
        // TODO: test posEntryModePan
    }

    /**
     * Test the property 'posEntryModePin'
     */
    @Test
    public void posEntryModePinTest() {
        // TODO: test posEntryModePin
    }

    /**
     * Test the property 'posTerminalAttendance'
     */
    @Test
    public void posTerminalAttendanceTest() {
        // TODO: test posTerminalAttendance
    }

    /**
     * Test the property 'posTerminalLocation'
     */
    @Test
    public void posTerminalLocationTest() {
        // TODO: test posTerminalLocation
    }

    /**
     * Test the property 'posTransactionStatus'
     */
    @Test
    public void posTransactionStatusTest() {
        // TODO: test posTransactionStatus
    }

    /**
     * Test the property 'primaryAccountNumber'
     */
    @Test
    public void primaryAccountNumberTest() {
        // TODO: test primaryAccountNumber
    }

    /**
     * Test the property 'primaryAccountNumberAccountRange'
     */
    @Test
    public void primaryAccountNumberAccountRangeTest() {
        // TODO: test primaryAccountNumberAccountRange
    }

    /**
     * Test the property 'privateData'
     */
    @Test
    public void privateDataTest() {
        // TODO: test privateData
    }

    /**
     * Test the property 'processingCode'
     */
    @Test
    public void processingCodeTest() {
        // TODO: test processingCode
    }

    /**
     * Test the property 'recordDataPresenceIndicator'
     */
    @Test
    public void recordDataPresenceIndicatorTest() {
        // TODO: test recordDataPresenceIndicator
    }

    /**
     * Test the property 'responseCode'
     */
    @Test
    public void responseCodeTest() {
        // TODO: test responseCode
    }

    /**
     * Test the property 'retrievalReferenceNumber'
     */
    @Test
    public void retrievalReferenceNumberTest() {
        // TODO: test retrievalReferenceNumber
    }

    /**
     * Test the property 'settlementActualAmount'
     */
    @Test
    public void settlementActualAmountTest() {
        // TODO: test settlementActualAmount
    }

    /**
     * Test the property 'settlementDate'
     */
    @Test
    public void settlementDateTest() {
        // TODO: test settlementDate
    }

    /**
     * Test the property 'stan'
     */
    @Test
    public void stanTest() {
        // TODO: test stan
    }

    /**
     * Test the property 'storageTechnology'
     */
    @Test
    public void storageTechnologyTest() {
        // TODO: test storageTechnology
    }

    /**
     * Test the property 'systemsTraceAuditNumber'
     */
    @Test
    public void systemsTraceAuditNumberTest() {
        // TODO: test systemsTraceAuditNumber
    }

    /**
     * Test the property 'tokenAssuranceLevel'
     */
    @Test
    public void tokenAssuranceLevelTest() {
        // TODO: test tokenAssuranceLevel
    }

    /**
     * Test the property 'tokenRequestorId'
     */
    @Test
    public void tokenRequestorIdTest() {
        // TODO: test tokenRequestorId
    }

    /**
     * Test the property 'track1'
     */
    @Test
    public void track1Test() {
        // TODO: test track1
    }

    /**
     * Test the property 'track2'
     */
    @Test
    public void track2Test() {
        // TODO: test track2
    }

    /**
     * Test the property 'transactionActualAmount'
     */
    @Test
    public void transactionActualAmountTest() {
        // TODO: test transactionActualAmount
    }

    /**
     * Test the property 'transactionAmountLocal'
     */
    @Test
    public void transactionAmountLocalTest() {
        // TODO: test transactionAmountLocal
    }

    /**
     * Test the property 'transactionCategoryCode'
     */
    @Test
    public void transactionCategoryCodeTest() {
        // TODO: test transactionCategoryCode
    }

    /**
     * Test the property 'transactionCurrencyCode'
     */
    @Test
    public void transactionCurrencyCodeTest() {
        // TODO: test transactionCurrencyCode
    }

    /**
     * Test the property 'transactionType'
     */
    @Test
    public void transactionTypeTest() {
        // TODO: test transactionType
    }

    /**
     * Test the property 'transmissionDateAndTime'
     */
    @Test
    public void transmissionDateAndTimeTest() {
        // TODO: test transmissionDateAndTime
    }

    /**
     * Test the property 'universalCardholderAuthenticationFieldUcaf'
     */
    @Test
    public void universalCardholderAuthenticationFieldUcafTest() {
        // TODO: test universalCardholderAuthenticationFieldUcaf
    }

    /**
     * Test the property 'vcnProductCode'
     */
    @Test
    public void vcnProductCodeTest() {
        // TODO: test vcnProductCode
    }

    /**
     * Test the property 'walletIdentifier'
     */
    @Test
    public void walletIdentifierTest() {
        // TODO: test walletIdentifier
    }

}
