/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import bp4.mastercom_api_client.model.CaseFilingIdSourceRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CaseFilingClaimsRequest
 */
public class CaseFilingClaimsRequestTest {
    private final CaseFilingClaimsRequest model = new CaseFilingClaimsRequest();

    /**
     * Model tests for CaseFilingClaimsRequest
     */
    @Test
    public void testCaseFilingClaimsRequest() {
        // TODO: test CaseFilingClaimsRequest
    }

    /**
     * Test the property 'caseFilingList'
     */
    @Test
    public void caseFilingListTest() {
        // TODO: test caseFilingList
    }

}
