/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OriginalInformationInstallments
 */
public class OriginalInformationInstallmentsTest {
    private final OriginalInformationInstallments model = new OriginalInformationInstallments();

    /**
     * Model tests for OriginalInformationInstallments
     */
    @Test
    public void testOriginalInformationInstallments() {
        // TODO: test OriginalInformationInstallments
    }

    /**
     * Test the property 'amountOfPurchase'
     */
    @Test
    public void amountOfPurchaseTest() {
        // TODO: test amountOfPurchase
    }

    /**
     * Test the property 'transactionInterestRate'
     */
    @Test
    public void transactionInterestRateTest() {
        // TODO: test transactionInterestRate
    }

    /**
     * Test the property 'installmentAmount'
     */
    @Test
    public void installmentAmountTest() {
        // TODO: test installmentAmount
    }

}
