/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrievalsImageStatusResponseStructure
 */
public class RetrievalsImageStatusResponseStructureTest {
    private final RetrievalsImageStatusResponseStructure model = new RetrievalsImageStatusResponseStructure();

    /**
     * Model tests for RetrievalsImageStatusResponseStructure
     */
    @Test
    public void testRetrievalsImageStatusResponseStructure() {
        // TODO: test RetrievalsImageStatusResponseStructure
    }

    /**
     * Test the property 'claimId'
     */
    @Test
    public void claimIdTest() {
        // TODO: test claimId
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
