/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionInformationEbdfStructure
 */
public class TransactionInformationEbdfStructureTest {
    private final TransactionInformationEbdfStructure model = new TransactionInformationEbdfStructure();

    /**
     * Model tests for TransactionInformationEbdfStructure
     */
    @Test
    public void testTransactionInformationEbdfStructure() {
        // TODO: test TransactionInformationEbdfStructure
    }

    /**
     * Test the property 'acquirerRefDataOrSwitchSerialNum'
     */
    @Test
    public void acquirerRefDataOrSwitchSerialNumTest() {
        // TODO: test acquirerRefDataOrSwitchSerialNum
    }

    /**
     * Test the property 'merchantName'
     */
    @Test
    public void merchantNameTest() {
        // TODO: test merchantName
    }

    /**
     * Test the property 'transactionOrSettlementDate'
     */
    @Test
    public void transactionOrSettlementDateTest() {
        // TODO: test transactionOrSettlementDate
    }

    /**
     * Test the property 'disputedAmount'
     */
    @Test
    public void disputedAmountTest() {
        // TODO: test disputedAmount
    }

}
