/*
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bp4.mastercom_api_client.model;

import bp4.mastercom_api_client.model.DocumentStructure;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateCaseRequest
 */
public class UpdateCaseRequestTest {
    private final UpdateCaseRequest model = new UpdateCaseRequest();

    /**
     * Model tests for UpdateCaseRequest
     */
    @Test
    public void testUpdateCaseRequest() {
        // TODO: test UpdateCaseRequest
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'fileAttachment'
     */
    @Test
    public void fileAttachmentTest() {
        // TODO: test fileAttachment
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'rebuttedAs'
     */
    @Test
    public void rebuttedAsTest() {
        // TODO: test rebuttedAs
    }

    /**
     * Test the property 'docRetryAs'
     */
    @Test
    public void docRetryAsTest() {
        // TODO: test docRetryAs
    }

}
